// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// external module LZC

module BarrelShifter(	// src/main/scala/pvu/BarrelShift.scala:13:7
  input  [14:0] io_operand_i,	// src/main/scala/pvu/BarrelShift.scala:14:14
  input  [3:0]  io_shift_amount,	// src/main/scala/pvu/BarrelShift.scala:14:14
  output [14:0] io_result_o	// src/main/scala/pvu/BarrelShift.scala:14:14
);

  wire [14:0] _temp_results_2_T_2 =
    io_shift_amount[3] ? {io_operand_i[6:0], 8'h0} : io_operand_i;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [14:0] _temp_results_1_T_2 =
    io_shift_amount[2] ? {_temp_results_2_T_2[10:0], 4'h0} : _temp_results_2_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [14:0] _temp_results_0_T_2 =
    io_shift_amount[1] ? {_temp_results_1_T_2[12:0], 2'h0} : _temp_results_1_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{27,33,49,70}
  assign io_result_o =
    io_shift_amount[0] ? {_temp_results_0_T_2[13:0], 1'h0} : _temp_results_0_T_2;	// src/main/scala/pvu/BarrelShift.scala:13:7, :32:33, :42:{23,39,60}
endmodule

module PositDecode(	// src/main/scala/pvu/PositDecode.scala:7:7
  input  [0:0][15:0] io_posit,	// src/main/scala/pvu/PositDecode.scala:13:14
  output [0:0]       io_Sign,	// src/main/scala/pvu/PositDecode.scala:13:14
  output [0:0][6:0]  io_Exp,	// src/main/scala/pvu/PositDecode.scala:13:14
  output [0:0][11:0] io_Frac	// src/main/scala/pvu/PositDecode.scala:13:14
);

  wire [14:0] _barrel_shifter_io_result_o;	// src/main/scala/pvu/PositDecode.scala:64:32
  wire [3:0]  _lzcModule_cnt_o;	// src/main/scala/pvu/PositDecode.scala:41:27
  wire [14:0] _operand_0_T_6 =
    io_posit[1'h0][15] ? ~(io_posit[1'h0][14:0]) + 15'h1 : io_posit[1'h0][14:0];	// src/main/scala/pvu/PositDecode.scala:24:30, :25:{22,44,56,77}, :55:46
  LZC #(
    .MODE(1),
    .WIDTH(15)
  ) lzcModule (	// src/main/scala/pvu/PositDecode.scala:41:27
    .in_i    ({15{_operand_0_T_6[14]}} ^ _operand_0_T_6),	// src/main/scala/pvu/PositDecode.scala:25:22, :35:33, :36:26
    .cnt_o   (_lzcModule_cnt_o),
    .empty_o (/* unused */)
  );
  BarrelShifter barrel_shifter (	// src/main/scala/pvu/PositDecode.scala:64:32
    .io_operand_i    (_operand_0_T_6),	// src/main/scala/pvu/PositDecode.scala:25:22
    .io_shift_amount (_lzcModule_cnt_o + 4'h1),	// src/main/scala/pvu/PositDecode.scala:41:27, :55:67, :66:54
    .io_result_o     (_barrel_shifter_io_result_o)
  );
  assign io_Sign = {1{io_posit[1'h0][15]}};	// src/main/scala/pvu/PositDecode.scala:7:7, :24:{16,30}, :55:46
  assign io_Exp =
    {1{{(_operand_0_T_6[14]
           ? {1'h0, _lzcModule_cnt_o - 4'h1}
           : {1'h1, ~_lzcModule_cnt_o + 4'h1}) | {5{_barrel_shifter_io_result_o[14]}},
        _barrel_shifter_io_result_o[14:13]}}};	// src/main/scala/pvu/PositDecode.scala:7:7, :25:{22,34}, :35:33, :41:27, :55:{27,46,67,78,84,100}, :64:32, :73:73, :74:39
  assign io_Frac = {1{{|_operand_0_T_6, _barrel_shifter_io_result_o[12:2]}}};	// src/main/scala/pvu/PositDecode.scala:7:7, :25:22, :64:32, :80:56, :81:{22,63}
endmodule

module FractionAlignment_AddSub(	// src/main/scala/pvu/FractionAlignment_AddSub.scala:7:7
  input  [0:0][11:0] io_pir_frac1_i,	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
                     io_pir_frac2_i,	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
  input  [0:0][6:0]  io_pir_exp1_i,	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
                     io_pir_exp2_i,	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
  output [0:0][13:0] io_pir_frac1_align,	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
                     io_pir_frac2_align,	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
  output [0:0][6:0]  io_pir_max_exp	// src/main/scala/pvu/FractionAlignment_AddSub.scala:14:14
);

  wire [6:0]  _io_pir_max_exp_0_T_1 =
    $signed(io_pir_exp1_i[1'h0]) > $signed(io_pir_exp2_i[1'h0])
      ? io_pir_exp1_i[1'h0]
      : io_pir_exp2_i[1'h0];	// src/main/scala/pvu/FractionAlignment_AddSub.scala:27:{29,47}, :38:45
  wire [13:0] _frac1_shifted_0_T = {io_pir_frac1_i[1'h0], 2'h0};	// src/main/scala/pvu/FractionAlignment_AddSub.scala:37:45, :38:45
  wire [13:0] _frac2_shifted_0_T = {io_pir_frac2_i[1'h0], 2'h0};	// src/main/scala/pvu/FractionAlignment_AddSub.scala:37:45, :38:45
  wire [6:0]  _shift_amount1_T = _io_pir_max_exp_0_T_1 - io_pir_exp1_i[1'h0];	// src/main/scala/pvu/FractionAlignment_AddSub.scala:27:{29,47}, :38:45, :50:44
  wire [6:0]  _shift_amount2_T = _io_pir_max_exp_0_T_1 - io_pir_exp2_i[1'h0];	// src/main/scala/pvu/FractionAlignment_AddSub.scala:27:{29,47}, :38:45, :51:44
  wire        _GEN = ~(|_shift_amount1_T) & (|_shift_amount2_T);	// src/main/scala/pvu/FractionAlignment_AddSub.scala:50:44, :51:44, :53:{24,32,49}
  wire [13:0] _GEN_0 = {2'h0, io_pir_frac1_i[1'h0]};	// src/main/scala/pvu/FractionAlignment_AddSub.scala:37:45, :38:45, :54:29
  wire        _GEN_1 = ~(|_shift_amount2_T) & (|_shift_amount1_T);	// src/main/scala/pvu/FractionAlignment_AddSub.scala:50:44, :51:44, :53:{24,49}, :56:{30,38}
  wire        _GEN_2 = ~(|_shift_amount1_T) & ~(|_shift_amount2_T);	// src/main/scala/pvu/FractionAlignment_AddSub.scala:50:44, :51:44, :53:{24,49}, :56:30, :59:38
  assign io_pir_frac1_align =
    {1{_GEN
         ? _GEN_0
         : _GEN_1
             ? _frac1_shifted_0_T >> (_shift_amount1_T > 7'hE ? 7'hE : _shift_amount1_T)
             : _GEN_2
                 ? _GEN_0
                 : _frac1_shifted_0_T
                   >> (_shift_amount1_T > 7'hE ? 7'hE : _shift_amount1_T)}};	// src/main/scala/pvu/FractionAlignment_AddSub.scala:7:7, :37:45, :50:44, :53:{32,57}, :54:29, :55:55, :56:{38,63}, :58:{29,49,55,70}, :59:{38,63}, :60:29, :64:{27,47,53,68}
  assign io_pir_frac2_align =
    {1{_GEN
         ? _frac2_shifted_0_T >> (_shift_amount2_T > 7'hE ? 7'hE : _shift_amount2_T)
         : _GEN_1 | _GEN_2
             ? {2'h0, io_pir_frac2_i[1'h0]}
             : _frac2_shifted_0_T
               >> (_shift_amount2_T > 7'hE ? 7'hE : _shift_amount2_T)}};	// src/main/scala/pvu/FractionAlignment_AddSub.scala:7:7, :37:45, :38:45, :51:44, :53:{32,57}, :55:{29,49,55,70}, :56:{38,63}, :57:29, :59:{38,63}, :65:{47,53,68}
  assign io_pir_max_exp = {1{_io_pir_max_exp_0_T_1}};	// src/main/scala/pvu/FractionAlignment_AddSub.scala:7:7, :27:{23,29}
endmodule

module Add(	// src/main/scala/pvu/Add.scala:7:7
  input  [0:0]       io_pir_sign1_i,	// src/main/scala/pvu/Add.scala:13:14
                     io_pir_sign2_i,	// src/main/scala/pvu/Add.scala:13:14
  input  [0:0][6:0]  io_pir_exp1_i,	// src/main/scala/pvu/Add.scala:13:14
                     io_pir_exp2_i,	// src/main/scala/pvu/Add.scala:13:14
  input  [0:0][13:0] io_pir_frac1_aligned,	// src/main/scala/pvu/Add.scala:13:14
                     io_pir_frac2_aligned,	// src/main/scala/pvu/Add.scala:13:14
  output [0:0]       io_pir_sign_o,	// src/main/scala/pvu/Add.scala:13:14
  output [0:0][6:0]  io_pir_exp_o,	// src/main/scala/pvu/Add.scala:13:14
  output [0:0][13:0] io_pir_frac_o,	// src/main/scala/pvu/Add.scala:13:14
  output [0:0]       io_overflow,	// src/main/scala/pvu/Add.scala:13:14
                     io_frac_truncate	// src/main/scala/pvu/Add.scala:13:14
);

  wire        _GEN = io_pir_sign1_i[1'h0] == io_pir_sign2_i[1'h0];	// src/main/scala/pvu/Add.scala:31:{24,43}
  wire [14:0] sum =
    {1'h0, io_pir_frac1_aligned[1'h0]} + {1'h0, io_pir_frac2_aligned[1'h0]};	// src/main/scala/pvu/Add.scala:31:24, :38:41
  wire        mant1_greater = io_pir_frac1_aligned[1'h0] > io_pir_frac2_aligned[1'h0];	// src/main/scala/pvu/Add.scala:31:24, :38:41, :59:32
  assign io_pir_sign_o =
    {1{_GEN | mant1_greater ? io_pir_sign1_i[1'h0] : io_pir_sign2_i[1'h0]}};	// src/main/scala/pvu/Add.scala:7:7, :31:{24,43}, :36:31, :46:22, :59:32, :66:23, :67:22
  assign io_pir_exp_o =
    {1{_GEN & sum[14] ? io_pir_exp1_i[1'h0] + 7'h1 : io_pir_exp1_i[1'h0]}};	// src/main/scala/pvu/Add.scala:7:7, :31:{24,43}, :36:31, :38:41, :39:20, :43:{23,48}, :47:22, :70:25
  assign io_pir_frac_o =
    {1{_GEN
         ? (sum[14] ? sum[14:1] : sum[13:0])
         : mant1_greater
             ? io_pir_frac1_aligned[1'h0] - io_pir_frac2_aligned[1'h0]
             : io_pir_frac2_aligned[1'h0] - io_pir_frac1_aligned[1'h0]}};	// src/main/scala/pvu/Add.scala:7:7, :31:{24,43}, :36:31, :38:41, :39:20, :42:{23,35,44}, :48:22, :59:32, :62:{24,46,61}, :63:22
  assign io_overflow = {1{_GEN & sum[14]}};	// src/main/scala/pvu/Add.scala:7:7, :31:43, :36:31, :38:41, :39:20, :51:20, :71:25
  assign io_frac_truncate = {1{_GEN & sum[14] & (|(sum[13:0]))}};	// src/main/scala/pvu/Add.scala:7:7, :31:43, :36:31, :38:41, :39:20, :42:44, :54:{25,69}, :72:25
endmodule

module Sub(	// src/main/scala/pvu/Sub.scala:7:7
  input  [0:0]       io_pir_sign1_i,	// src/main/scala/pvu/Sub.scala:14:14
                     io_pir_sign2_i,	// src/main/scala/pvu/Sub.scala:14:14
  input  [0:0][6:0]  io_pir_exp1_i,	// src/main/scala/pvu/Sub.scala:14:14
                     io_pir_exp2_i,	// src/main/scala/pvu/Sub.scala:14:14
  input  [0:0][13:0] io_pir_frac1_aligned,	// src/main/scala/pvu/Sub.scala:14:14
                     io_pir_frac2_aligned,	// src/main/scala/pvu/Sub.scala:14:14
  output [0:0]       io_pir_sign_o,	// src/main/scala/pvu/Sub.scala:14:14
  output [0:0][6:0]  io_pir_exp_o,	// src/main/scala/pvu/Sub.scala:14:14
  output [0:0][13:0] io_pir_frac_o,	// src/main/scala/pvu/Sub.scala:14:14
  output [0:0]       io_overflow,	// src/main/scala/pvu/Sub.scala:14:14
                     io_frac_truncate	// src/main/scala/pvu/Sub.scala:14:14
);

  wire        _GEN = io_pir_sign1_i[1'h0] == io_pir_sign2_i[1'h0];	// src/main/scala/pvu/Sub.scala:32:{24,43}
  wire        mant1_greater = io_pir_frac1_aligned[1'h0] > io_pir_frac2_aligned[1'h0];	// src/main/scala/pvu/Sub.scala:32:24, :41:34
  wire [14:0] sum =
    {1'h0, io_pir_frac1_aligned[1'h0]} + {1'h0, io_pir_frac2_aligned[1'h0]};	// src/main/scala/pvu/Sub.scala:32:24, :41:34, :44:52, :59:46
  assign io_pir_sign_o = {1{_GEN & ~mant1_greater ^ io_pir_sign1_i[1'h0]}};	// src/main/scala/pvu/Sub.scala:7:7, :32:{24,43}, :37:31, :41:34, :47:38, :48:26, :50:26, :65:24
  assign io_pir_exp_o =
    {1{_GEN | ~(sum[14]) ? io_pir_exp1_i[1'h0] : io_pir_exp1_i[1'h0] + 7'h1}};	// src/main/scala/pvu/Sub.scala:7:7, :32:{24,43}, :37:31, :54:27, :59:46, :60:25, :62:50, :66:24
  assign io_pir_frac_o =
    {1{_GEN
         ? (mant1_greater
              ? io_pir_frac1_aligned[1'h0] - io_pir_frac2_aligned[1'h0]
              : io_pir_frac2_aligned[1'h0] - io_pir_frac1_aligned[1'h0])
         : sum[14] ? sum[14:1] : sum[13:0]}};	// src/main/scala/pvu/Sub.scala:7:7, :32:{24,43}, :37:31, :41:34, :44:{24,30,52,67}, :59:46, :60:25, :61:{25,37,46}, :67:24
  assign io_overflow = {1{~_GEN & sum[14]}};	// src/main/scala/pvu/Sub.scala:7:7, :32:43, :37:31, :55:27, :59:46, :60:25, :70:23
  assign io_frac_truncate = {1{~_GEN & sum[14] & (|(sum[13:0]))}};	// src/main/scala/pvu/Sub.scala:7:7, :32:43, :37:31, :55:27, :56:27, :59:46, :60:25, :61:46, :70:23, :71:{27,62}
endmodule

module BoothEncoder(	// src/main/scala/pvu/BoothEncoder.scala:19:7
  input  [2:0] io_code,	// src/main/scala/pvu/BoothEncoder.scala:20:14
  output       io_neg,	// src/main/scala/pvu/BoothEncoder.scala:20:14
               io_zero,	// src/main/scala/pvu/BoothEncoder.scala:20:14
               io_one,	// src/main/scala/pvu/BoothEncoder.scala:20:14
               io_two	// src/main/scala/pvu/BoothEncoder.scala:20:14
);

  assign io_neg = io_code[2] & ~(io_code[0]) | io_code[2] & ~(io_code[1]);	// src/main/scala/pvu/BoothEncoder.scala:19:7, :30:{21,25,27,35,40,54,56,64}
  assign io_zero = io_code == 3'h0 | (&io_code);	// src/main/scala/pvu/BoothEncoder.scala:19:7, :34:{24,29,40}
  assign io_one = io_code[1] & ~(io_code[0]) | ~(io_code[1]) & io_code[0];	// src/main/scala/pvu/BoothEncoder.scala:19:7, :30:{35,64}, :42:{25,27,40,43,55}
  assign io_two =
    ~(io_code[2]) & io_code[1] & io_code[0] | io_code[2] & ~(io_code[1]) & ~(io_code[0]);	// src/main/scala/pvu/BoothEncoder.scala:19:7, :30:{21,35,64}, :38:{14,39,53,69,81,83}
endmodule

module GenProduct(	// src/main/scala/pvu/GenProduct.scala:17:7
  input  [13:0] io_multiplicand,	// src/main/scala/pvu/GenProduct.scala:18:14
  input  [2:0]  io_code,	// src/main/scala/pvu/GenProduct.scala:18:14
  output [14:0] io_partial_prod,	// src/main/scala/pvu/GenProduct.scala:18:14
  output        io_sign	// src/main/scala/pvu/GenProduct.scala:18:14
);

  wire _boothEncoder_io_neg;	// src/main/scala/pvu/GenProduct.scala:26:28
  wire _boothEncoder_io_one;	// src/main/scala/pvu/GenProduct.scala:26:28
  wire _boothEncoder_io_two;	// src/main/scala/pvu/GenProduct.scala:26:28
  BoothEncoder boothEncoder (	// src/main/scala/pvu/GenProduct.scala:26:28
    .io_code (io_code),
    .io_neg  (_boothEncoder_io_neg),
    .io_zero (/* unused */),
    .io_one  (_boothEncoder_io_one),
    .io_two  (_boothEncoder_io_two)
  );
  assign io_partial_prod =
    {15{_boothEncoder_io_neg}}
    ^ (_boothEncoder_io_one
         ? {1'h0, io_multiplicand}
         : _boothEncoder_io_two ? {io_multiplicand, 1'h0} : 15'h0);	// src/main/scala/pvu/GenProduct.scala:17:7, :26:28, :33:30, :34:14, :35:37, :36:{14,33}, :38:14, :42:25
  assign io_sign = _boothEncoder_io_neg;	// src/main/scala/pvu/GenProduct.scala:17:7, :26:28
endmodule

module GenProds(	// src/main/scala/pvu/GenProds.scala:23:7
  input  [13:0]      io_operand_a,	// src/main/scala/pvu/GenProds.scala:27:14
                     io_operand_b,	// src/main/scala/pvu/GenProds.scala:27:14
  output [7:0][27:0] io_partial_prods	// src/main/scala/pvu/GenProds.scala:27:14
);

  wire [14:0] _genProdLast_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:81:27
  wire [14:0] _genProd_5_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_5_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [14:0] _genProd_4_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_4_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [14:0] _genProd_3_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_3_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [14:0] _genProd_2_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_2_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [14:0] _genProd_1_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_1_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [14:0] _genProd_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [14:0] _genProd0_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:45:24
  wire        _genProd0_io_sign;	// src/main/scala/pvu/GenProds.scala:45:24
  GenProduct genProd0 (	// src/main/scala/pvu/GenProds.scala:45:24
    .io_multiplicand (io_operand_a),
    .io_code         ({io_operand_b[1:0], 1'h0}),	// src/main/scala/pvu/GenProds.scala:35:24, :42:25
    .io_partial_prod (_genProd0_io_partial_prod),
    .io_sign         (_genProd0_io_sign)
  );
  GenProduct genProd (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[3:1]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_io_partial_prod),
    .io_sign         (_genProd_io_sign)
  );
  GenProduct genProd_1 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[5:3]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_1_io_partial_prod),
    .io_sign         (_genProd_1_io_sign)
  );
  GenProduct genProd_2 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[7:5]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_2_io_partial_prod),
    .io_sign         (_genProd_2_io_sign)
  );
  GenProduct genProd_3 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[9:7]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_3_io_partial_prod),
    .io_sign         (_genProd_3_io_sign)
  );
  GenProduct genProd_4 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[11:9]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_4_io_partial_prod),
    .io_sign         (_genProd_4_io_sign)
  );
  GenProduct genProd_5 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[13:11]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_5_io_partial_prod),
    .io_sign         (_genProd_5_io_sign)
  );
  GenProduct genProdLast (	// src/main/scala/pvu/GenProds.scala:81:27
    .io_multiplicand (io_operand_a),
    .io_code         ({2'h0, io_operand_b[13]}),	// src/main/scala/pvu/GenProds.scala:35:24, :78:33
    .io_partial_prod (_genProdLast_io_partial_prod),
    .io_sign         (/* unused */)
  );
  assign io_partial_prods =
    {{{_genProdLast_io_partial_prod[13:0], 1'h0, _genProd_5_io_sign, 12'h0}},
     {{1'h0, _genProd_5_io_partial_prod, 1'h0, _genProd_4_io_sign, 10'h0}},
     {{3'h0, _genProd_4_io_partial_prod, 1'h0, _genProd_3_io_sign, 8'h0}},
     {{5'h0, _genProd_3_io_partial_prod, 1'h0, _genProd_2_io_sign, 6'h0}},
     {{7'h0, _genProd_2_io_partial_prod, 1'h0, _genProd_1_io_sign, 4'h0}},
     {{9'h0, _genProd_1_io_partial_prod, 1'h0, _genProd_io_sign, 2'h0}},
     {{11'h0, _genProd_io_partial_prod, 1'h0, _genProd0_io_sign}},
     {{13'h0, _genProd0_io_partial_prod}}};	// src/main/scala/pvu/GenProds.scala:23:7, :35:24, :45:24, :52:23, :59:25, :74:{42,58}, :81:27, :94:{52,72}
endmodule

module Compressor4to2(	// src/main/scala/pvu/Compressor4to2.scala:7:7
  input  [3:0][27:0] io_operands_i,	// src/main/scala/pvu/Compressor4to2.scala:8:14
  output [29:0]      io_sum_o,	// src/main/scala/pvu/Compressor4to2.scala:8:14
                     io_carry_o	// src/main/scala/pvu/Compressor4to2.scala:8:14
);

  assign io_sum_o =
    {2'h0,
     io_operands_i[2'h0] ^ io_operands_i[2'h1] ^ io_operands_i[2'h2]
       ^ io_operands_i[2'h3]};	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :23:12
  assign io_carry_o =
    {2'h0,
     io_operands_i[2'h0] & io_operands_i[2'h1] | io_operands_i[2'h1] & io_operands_i[2'h2]
       | io_operands_i[2'h2] & io_operands_i[2'h3] | io_operands_i[2'h0]
       & io_operands_i[2'h2] | io_operands_i[2'h0] & io_operands_i[2'h3]
       | io_operands_i[2'h1] & io_operands_i[2'h3]};	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :16:33, :17:33, :18:33, :19:33, :20:{33,53}, :21:33, :24:14
endmodule

module CsaTree(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [3:0][27:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [29:0]      io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                     io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  Compressor4to2 compressor (	// src/main/scala/pvu/CsaTree.scala:39:28
    .io_operands_i (io_operands_i),
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module Compressor4to2_2(	// src/main/scala/pvu/Compressor4to2.scala:7:7
  input  [3:0][30:0] io_operands_i,	// src/main/scala/pvu/Compressor4to2.scala:8:14
  output [30:0]      io_sum_o,	// src/main/scala/pvu/Compressor4to2.scala:8:14
                     io_carry_o	// src/main/scala/pvu/Compressor4to2.scala:8:14
);

  assign io_sum_o =
    io_operands_i[2'h0] ^ io_operands_i[2'h1] ^ io_operands_i[2'h2] ^ io_operands_i[2'h3];	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36
  assign io_carry_o =
    io_operands_i[2'h0] & io_operands_i[2'h1] | io_operands_i[2'h1] & io_operands_i[2'h2]
    | io_operands_i[2'h2] & io_operands_i[2'h3] | io_operands_i[2'h0]
    & io_operands_i[2'h2] | io_operands_i[2'h0] & io_operands_i[2'h3]
    | io_operands_i[2'h1] & io_operands_i[2'h3];	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :16:33, :17:33, :18:33, :19:33, :20:{33,53}, :21:33
endmodule

module CsaTree_2(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [7:0][27:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [30:0]      io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                     io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  wire [29:0] _csa_tree_B_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [29:0] _csa_tree_B_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [29:0] _csa_tree_A_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  wire [29:0] _csa_tree_A_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  CsaTree csa_tree_A (	// src/main/scala/pvu/CsaTree.scala:50:28
    .io_operands_i (io_operands_i[3'h0 +: 4]),	// src/main/scala/pvu/CsaTree.scala:50:28, :51:30
    .io_sum_o      (_csa_tree_A_io_sum_o),
    .io_carry_o    (_csa_tree_A_io_carry_o)
  );
  CsaTree csa_tree_B (	// src/main/scala/pvu/CsaTree.scala:53:28
    .io_operands_i (io_operands_i[3'h4 +: 4]),	// src/main/scala/pvu/CsaTree.scala:53:28, :54:30
    .io_sum_o      (_csa_tree_B_io_sum_o),
    .io_carry_o    (_csa_tree_B_io_carry_o)
  );
  Compressor4to2_2 compressor (	// src/main/scala/pvu/CsaTree.scala:66:28
    .io_operands_i
      ({{{1'h0, _csa_tree_B_io_carry_o}},
        {{1'h0, _csa_tree_B_io_sum_o}},
        {{1'h0, _csa_tree_A_io_carry_o}},
        {{1'h0, _csa_tree_A_io_sum_o}}}),	// src/main/scala/pvu/CsaTree.scala:50:28, :53:28, :57:28, :58:18
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module Radix4BoothMultiplier(	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:7:7
  input  [13:0] io_operand_a,	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
                io_operand_b,	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
  output [27:0] io_sum_o,	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
                io_carry_o	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
);

  wire [30:0]      _csaTree_io_sum_o;	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:25:23
  wire [30:0]      _csaTree_io_carry_o;	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:25:23
  wire [7:0][27:0] _genProds_io_partial_prods;	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:20:24
  GenProds genProds (	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:20:24
    .io_operand_a     (io_operand_a),
    .io_operand_b     (io_operand_b),
    .io_partial_prods (_genProds_io_partial_prods)
  );
  CsaTree_2 csaTree (	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:25:23
    .io_operands_i (_genProds_io_partial_prods),	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:20:24
    .io_sum_o      (_csaTree_io_sum_o),
    .io_carry_o    (_csaTree_io_carry_o)
  );
  assign io_sum_o = _csaTree_io_sum_o[27:0];	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:7:7, :25:23, :29:14
  assign io_carry_o = _csaTree_io_carry_o[27:0];	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:7:7, :25:23, :30:14
endmodule

module Mul(	// src/main/scala/pvu/Mul.scala:7:7
  input  [0:0]       io_pir_sign1_i,	// src/main/scala/pvu/Mul.scala:14:14
                     io_pir_sign2_i,	// src/main/scala/pvu/Mul.scala:14:14
  input  [0:0][6:0]  io_pir_exp1_i,	// src/main/scala/pvu/Mul.scala:14:14
                     io_pir_exp2_i,	// src/main/scala/pvu/Mul.scala:14:14
  input  [0:0][13:0] io_pir_frac1_i,	// src/main/scala/pvu/Mul.scala:14:14
                     io_pir_frac2_i,	// src/main/scala/pvu/Mul.scala:14:14
  output [0:0]       io_pir_sign_o,	// src/main/scala/pvu/Mul.scala:14:14
  output [0:0][6:0]  io_pir_exp_o,	// src/main/scala/pvu/Mul.scala:14:14
  output [0:0][29:0] io_pir_frac_o	// src/main/scala/pvu/Mul.scala:14:14
);

  wire [27:0] _radix4BoothMultiplier_io_sum_o;	// src/main/scala/pvu/Mul.scala:38:39
  wire [27:0] _radix4BoothMultiplier_io_carry_o;	// src/main/scala/pvu/Mul.scala:38:39
  wire [7:0]  sum =
    {io_pir_exp1_i[1'h0][6], io_pir_exp1_i[1'h0]}
    + {io_pir_exp2_i[1'h0][6], io_pir_exp2_i[1'h0]};	// src/main/scala/pvu/Mul.scala:51:34
  wire        _GEN = /*cast(bit)*/io_pir_sign1_i;	// src/main/scala/pvu/Mul.scala:7:7
  wire        _GEN_0 = /*cast(bit)*/io_pir_sign2_i;	// src/main/scala/pvu/Mul.scala:7:7
  Radix4BoothMultiplier radix4BoothMultiplier (	// src/main/scala/pvu/Mul.scala:38:39
    .io_operand_a (io_pir_frac1_i[1'h0]),	// src/main/scala/pvu/Mul.scala:39:40, :51:34
    .io_operand_b (io_pir_frac2_i[1'h0]),	// src/main/scala/pvu/Mul.scala:40:40, :51:34
    .io_sum_o     (_radix4BoothMultiplier_io_sum_o),
    .io_carry_o   (_radix4BoothMultiplier_io_carry_o)
  );
  assign io_pir_sign_o = /*cast(bit[0:0])*/_GEN ^ _GEN_0;	// src/main/scala/pvu/Mul.scala:7:7
  assign io_pir_exp_o = {1{sum[7] ? 7'h3F : sum[6:0]}};	// src/main/scala/pvu/Mul.scala:7:7, :48:49, :51:34, :52:20, :54:{27,54}
  assign io_pir_frac_o =
    {1{sum[7]
         ? 30'h0
         : {2'h0, _radix4BoothMultiplier_io_sum_o}
           + {2'h0, _radix4BoothMultiplier_io_carry_o}}};	// src/main/scala/pvu/Mul.scala:7:7, :38:39, :43:55, :51:34, :52:20, :55:27
endmodule

module IntReciprocal(	// src/main/scala/pvu/IntReciprocal.scala:7:7
  input  [13:0] io_num_i,	// src/main/scala/pvu/IntReciprocal.scala:8:14
  output [27:0] io_reciprocal_o	// src/main/scala/pvu/IntReciprocal.scala:8:14
);

  wire [27:0] _GEN = {14'h0, io_num_i};	// src/main/scala/pvu/IntReciprocal.scala:17:23
  wire [27:0] x0 = 28'h4000 / _GEN;	// src/main/scala/pvu/IntReciprocal.scala:17:23
  wire [41:0] x1_x_new_full = {14'h0, x0} * {14'h0, 28'h8000 - _GEN * x0};	// src/main/scala/pvu/IntReciprocal.scala:17:23, :28:22, :35:20, :41:25
  wire [41:0] x2_x_new_full =
    {14'h0, x1_x_new_full[41:14]} * {14'h0, 28'h8000 - _GEN * x1_x_new_full[41:14]};	// src/main/scala/pvu/IntReciprocal.scala:17:23, :28:22, :35:20, :41:25, :44:{29,43}
  wire [41:0] x3_x_new_full =
    {14'h0, x2_x_new_full[41:14]} * {14'h0, 28'h8000 - _GEN * x2_x_new_full[41:14]};	// src/main/scala/pvu/IntReciprocal.scala:17:23, :28:22, :35:20, :41:25, :44:{29,43}
  assign io_reciprocal_o = x3_x_new_full[41:14];	// src/main/scala/pvu/IntReciprocal.scala:7:7, :41:25, :44:{29,43}
endmodule

module GenProduct_8(	// src/main/scala/pvu/GenProduct.scala:17:7
  input  [27:0] io_multiplicand,	// src/main/scala/pvu/GenProduct.scala:18:14
  input  [2:0]  io_code,	// src/main/scala/pvu/GenProduct.scala:18:14
  output [28:0] io_partial_prod,	// src/main/scala/pvu/GenProduct.scala:18:14
  output        io_sign	// src/main/scala/pvu/GenProduct.scala:18:14
);

  wire _boothEncoder_io_neg;	// src/main/scala/pvu/GenProduct.scala:26:28
  wire _boothEncoder_io_one;	// src/main/scala/pvu/GenProduct.scala:26:28
  wire _boothEncoder_io_two;	// src/main/scala/pvu/GenProduct.scala:26:28
  BoothEncoder boothEncoder (	// src/main/scala/pvu/GenProduct.scala:26:28
    .io_code (io_code),
    .io_neg  (_boothEncoder_io_neg),
    .io_zero (/* unused */),
    .io_one  (_boothEncoder_io_one),
    .io_two  (_boothEncoder_io_two)
  );
  assign io_partial_prod =
    {29{_boothEncoder_io_neg}}
    ^ (_boothEncoder_io_one
         ? {1'h0, io_multiplicand}
         : _boothEncoder_io_two ? {io_multiplicand, 1'h0} : 29'h0);	// src/main/scala/pvu/GenProduct.scala:17:7, :26:28, :33:30, :34:14, :35:37, :36:{14,33}, :38:14, :42:25
  assign io_sign = _boothEncoder_io_neg;	// src/main/scala/pvu/GenProduct.scala:17:7, :26:28
endmodule

module GenProds_1(	// src/main/scala/pvu/GenProds.scala:23:7
  input  [27:0]       io_operand_a,	// src/main/scala/pvu/GenProds.scala:27:14
                      io_operand_b,	// src/main/scala/pvu/GenProds.scala:27:14
  output [14:0][55:0] io_partial_prods	// src/main/scala/pvu/GenProds.scala:27:14
);

  wire [28:0] _genProdLast_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:81:27
  wire [28:0] _genProd_12_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_12_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_11_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_11_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_10_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_10_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_9_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_9_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_8_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_8_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_7_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_7_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_6_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_6_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_5_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_5_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_4_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_4_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_3_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_3_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_2_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_2_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_1_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_1_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:59:25
  wire        _genProd_io_sign;	// src/main/scala/pvu/GenProds.scala:59:25
  wire [28:0] _genProd0_io_partial_prod;	// src/main/scala/pvu/GenProds.scala:45:24
  wire        _genProd0_io_sign;	// src/main/scala/pvu/GenProds.scala:45:24
  GenProduct_8 genProd0 (	// src/main/scala/pvu/GenProds.scala:45:24
    .io_multiplicand (io_operand_a),
    .io_code         ({io_operand_b[1:0], 1'h0}),	// src/main/scala/pvu/GenProds.scala:35:24, :42:25
    .io_partial_prod (_genProd0_io_partial_prod),
    .io_sign         (_genProd0_io_sign)
  );
  GenProduct_8 genProd (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[3:1]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_io_partial_prod),
    .io_sign         (_genProd_io_sign)
  );
  GenProduct_8 genProd_1 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[5:3]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_1_io_partial_prod),
    .io_sign         (_genProd_1_io_sign)
  );
  GenProduct_8 genProd_2 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[7:5]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_2_io_partial_prod),
    .io_sign         (_genProd_2_io_sign)
  );
  GenProduct_8 genProd_3 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[9:7]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_3_io_partial_prod),
    .io_sign         (_genProd_3_io_sign)
  );
  GenProduct_8 genProd_4 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[11:9]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_4_io_partial_prod),
    .io_sign         (_genProd_4_io_sign)
  );
  GenProduct_8 genProd_5 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[13:11]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_5_io_partial_prod),
    .io_sign         (_genProd_5_io_sign)
  );
  GenProduct_8 genProd_6 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[15:13]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_6_io_partial_prod),
    .io_sign         (_genProd_6_io_sign)
  );
  GenProduct_8 genProd_7 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[17:15]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_7_io_partial_prod),
    .io_sign         (_genProd_7_io_sign)
  );
  GenProduct_8 genProd_8 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[19:17]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_8_io_partial_prod),
    .io_sign         (_genProd_8_io_sign)
  );
  GenProduct_8 genProd_9 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[21:19]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_9_io_partial_prod),
    .io_sign         (_genProd_9_io_sign)
  );
  GenProduct_8 genProd_10 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[23:21]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_10_io_partial_prod),
    .io_sign         (_genProd_10_io_sign)
  );
  GenProduct_8 genProd_11 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[25:23]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_11_io_partial_prod),
    .io_sign         (_genProd_11_io_sign)
  );
  GenProduct_8 genProd_12 (	// src/main/scala/pvu/GenProds.scala:59:25
    .io_multiplicand (io_operand_a),
    .io_code         (io_operand_b[27:25]),	// src/main/scala/pvu/GenProds.scala:56:27
    .io_partial_prod (_genProd_12_io_partial_prod),
    .io_sign         (_genProd_12_io_sign)
  );
  GenProduct_8 genProdLast (	// src/main/scala/pvu/GenProds.scala:81:27
    .io_multiplicand (io_operand_a),
    .io_code         ({2'h0, io_operand_b[27]}),	// src/main/scala/pvu/GenProds.scala:35:24, :78:33
    .io_partial_prod (_genProdLast_io_partial_prod),
    .io_sign         (/* unused */)
  );
  assign io_partial_prods =
    {{{_genProdLast_io_partial_prod[27:0], 1'h0, _genProd_12_io_sign, 26'h0}},
     {{1'h0, _genProd_12_io_partial_prod, 1'h0, _genProd_11_io_sign, 24'h0}},
     {{3'h0, _genProd_11_io_partial_prod, 1'h0, _genProd_10_io_sign, 22'h0}},
     {{5'h0, _genProd_10_io_partial_prod, 1'h0, _genProd_9_io_sign, 20'h0}},
     {{7'h0, _genProd_9_io_partial_prod, 1'h0, _genProd_8_io_sign, 18'h0}},
     {{9'h0, _genProd_8_io_partial_prod, 1'h0, _genProd_7_io_sign, 16'h0}},
     {{11'h0, _genProd_7_io_partial_prod, 1'h0, _genProd_6_io_sign, 14'h0}},
     {{13'h0, _genProd_6_io_partial_prod, 1'h0, _genProd_5_io_sign, 12'h0}},
     {{15'h0, _genProd_5_io_partial_prod, 1'h0, _genProd_4_io_sign, 10'h0}},
     {{17'h0, _genProd_4_io_partial_prod, 1'h0, _genProd_3_io_sign, 8'h0}},
     {{19'h0, _genProd_3_io_partial_prod, 1'h0, _genProd_2_io_sign, 6'h0}},
     {{21'h0, _genProd_2_io_partial_prod, 1'h0, _genProd_1_io_sign, 4'h0}},
     {{23'h0, _genProd_1_io_partial_prod, 1'h0, _genProd_io_sign, 2'h0}},
     {{25'h0, _genProd_io_partial_prod, 1'h0, _genProd0_io_sign}},
     {{27'h0, _genProd0_io_partial_prod}}};	// src/main/scala/pvu/GenProds.scala:23:7, :35:24, :42:12, :45:24, :52:23, :59:25, :74:{42,58}, :81:27, :94:{52,72}
endmodule

module Compressor3to2(	// src/main/scala/pvu/Compressor3to2.scala:7:7
  input  [2:0][55:0] io_operands_i,	// src/main/scala/pvu/Compressor3to2.scala:8:14
  output [57:0]      io_sum_o,	// src/main/scala/pvu/Compressor3to2.scala:8:14
                     io_carry_o	// src/main/scala/pvu/Compressor3to2.scala:8:14
);

  assign io_sum_o =
    {2'h0, io_operands_i[2'h0] ^ io_operands_i[2'h1] ^ io_operands_i[2'h2]};	// src/main/scala/pvu/Compressor3to2.scala:7:7, :15:36, :20:14
  assign io_carry_o =
    {2'h0,
     io_operands_i[2'h0] & io_operands_i[2'h1] | io_operands_i[2'h1] & io_operands_i[2'h2]
       | io_operands_i[2'h0] & io_operands_i[2'h2]};	// src/main/scala/pvu/Compressor3to2.scala:7:7, :15:36, :16:33, :17:{33,53}, :18:33, :21:14
endmodule

module CsaTree_3(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [2:0][55:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [57:0]      io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                     io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  Compressor3to2 compressor (	// src/main/scala/pvu/CsaTree.scala:32:28
    .io_operands_i (io_operands_i),
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module Compressor4to2_3(	// src/main/scala/pvu/Compressor4to2.scala:7:7
  input  [3:0][55:0] io_operands_i,	// src/main/scala/pvu/Compressor4to2.scala:8:14
  output [57:0]      io_sum_o,	// src/main/scala/pvu/Compressor4to2.scala:8:14
                     io_carry_o	// src/main/scala/pvu/Compressor4to2.scala:8:14
);

  assign io_sum_o =
    {2'h0,
     io_operands_i[2'h0] ^ io_operands_i[2'h1] ^ io_operands_i[2'h2]
       ^ io_operands_i[2'h3]};	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :23:12
  assign io_carry_o =
    {2'h0,
     io_operands_i[2'h0] & io_operands_i[2'h1] | io_operands_i[2'h1] & io_operands_i[2'h2]
       | io_operands_i[2'h2] & io_operands_i[2'h3] | io_operands_i[2'h0]
       & io_operands_i[2'h2] | io_operands_i[2'h0] & io_operands_i[2'h3]
       | io_operands_i[2'h1] & io_operands_i[2'h3]};	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :16:33, :17:33, :18:33, :19:33, :20:{33,53}, :21:33, :24:14
endmodule

module CsaTree_4(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [3:0][55:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [57:0]      io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                     io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  Compressor4to2_3 compressor (	// src/main/scala/pvu/CsaTree.scala:39:28
    .io_operands_i (io_operands_i),
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module Compressor4to2_4(	// src/main/scala/pvu/Compressor4to2.scala:7:7
  input  [3:0][58:0] io_operands_i,	// src/main/scala/pvu/Compressor4to2.scala:8:14
  output [58:0]      io_sum_o,	// src/main/scala/pvu/Compressor4to2.scala:8:14
                     io_carry_o	// src/main/scala/pvu/Compressor4to2.scala:8:14
);

  assign io_sum_o =
    io_operands_i[2'h0] ^ io_operands_i[2'h1] ^ io_operands_i[2'h2] ^ io_operands_i[2'h3];	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36
  assign io_carry_o =
    io_operands_i[2'h0] & io_operands_i[2'h1] | io_operands_i[2'h1] & io_operands_i[2'h2]
    | io_operands_i[2'h2] & io_operands_i[2'h3] | io_operands_i[2'h0]
    & io_operands_i[2'h2] | io_operands_i[2'h0] & io_operands_i[2'h3]
    | io_operands_i[2'h1] & io_operands_i[2'h3];	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :16:33, :17:33, :18:33, :19:33, :20:{33,53}, :21:33
endmodule

module CsaTree_5(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [6:0][55:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [58:0]      io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                     io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  wire [57:0] _csa_tree_B_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [57:0] _csa_tree_B_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [57:0] _csa_tree_A_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  wire [57:0] _csa_tree_A_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  CsaTree_3 csa_tree_A (	// src/main/scala/pvu/CsaTree.scala:50:28
    .io_operands_i (io_operands_i[3'h0 +: 3]),	// src/main/scala/pvu/CsaTree.scala:50:28, :51:30
    .io_sum_o      (_csa_tree_A_io_sum_o),
    .io_carry_o    (_csa_tree_A_io_carry_o)
  );
  CsaTree_4 csa_tree_B (	// src/main/scala/pvu/CsaTree.scala:53:28
    .io_operands_i (io_operands_i[3'h3 +: 4]),	// src/main/scala/pvu/CsaTree.scala:53:28, :54:30
    .io_sum_o      (_csa_tree_B_io_sum_o),
    .io_carry_o    (_csa_tree_B_io_carry_o)
  );
  Compressor4to2_4 compressor (	// src/main/scala/pvu/CsaTree.scala:66:28
    .io_operands_i
      ({{{1'h0, _csa_tree_B_io_carry_o}},
        {{1'h0, _csa_tree_B_io_sum_o}},
        {{1'h0, _csa_tree_A_io_carry_o}},
        {{1'h0, _csa_tree_A_io_sum_o}}}),	// src/main/scala/pvu/CsaTree.scala:50:28, :53:28, :57:28, :58:18
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module CsaTree_8(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [7:0][55:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [58:0]      io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                     io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  wire [57:0] _csa_tree_B_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [57:0] _csa_tree_B_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [57:0] _csa_tree_A_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  wire [57:0] _csa_tree_A_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  CsaTree_4 csa_tree_A (	// src/main/scala/pvu/CsaTree.scala:50:28
    .io_operands_i (io_operands_i[3'h0 +: 4]),	// src/main/scala/pvu/CsaTree.scala:50:28, :51:30
    .io_sum_o      (_csa_tree_A_io_sum_o),
    .io_carry_o    (_csa_tree_A_io_carry_o)
  );
  CsaTree_4 csa_tree_B (	// src/main/scala/pvu/CsaTree.scala:53:28
    .io_operands_i (io_operands_i[3'h4 +: 4]),	// src/main/scala/pvu/CsaTree.scala:53:28, :54:30
    .io_sum_o      (_csa_tree_B_io_sum_o),
    .io_carry_o    (_csa_tree_B_io_carry_o)
  );
  Compressor4to2_4 compressor (	// src/main/scala/pvu/CsaTree.scala:66:28
    .io_operands_i
      ({{{1'h0, _csa_tree_B_io_carry_o}},
        {{1'h0, _csa_tree_B_io_sum_o}},
        {{1'h0, _csa_tree_A_io_carry_o}},
        {{1'h0, _csa_tree_A_io_sum_o}}}),	// src/main/scala/pvu/CsaTree.scala:50:28, :53:28, :57:28, :58:18
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module Compressor4to2_8(	// src/main/scala/pvu/Compressor4to2.scala:7:7
  input  [3:0][59:0] io_operands_i,	// src/main/scala/pvu/Compressor4to2.scala:8:14
  output [59:0]      io_sum_o,	// src/main/scala/pvu/Compressor4to2.scala:8:14
                     io_carry_o	// src/main/scala/pvu/Compressor4to2.scala:8:14
);

  assign io_sum_o =
    io_operands_i[2'h0] ^ io_operands_i[2'h1] ^ io_operands_i[2'h2] ^ io_operands_i[2'h3];	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36
  assign io_carry_o =
    io_operands_i[2'h0] & io_operands_i[2'h1] | io_operands_i[2'h1] & io_operands_i[2'h2]
    | io_operands_i[2'h2] & io_operands_i[2'h3] | io_operands_i[2'h0]
    & io_operands_i[2'h2] | io_operands_i[2'h0] & io_operands_i[2'h3]
    | io_operands_i[2'h1] & io_operands_i[2'h3];	// src/main/scala/pvu/Compressor4to2.scala:7:7, :15:36, :16:33, :17:33, :18:33, :19:33, :20:{33,53}, :21:33
endmodule

module CsaTree_9(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [14:0][55:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [59:0]       io_sum_o,	// src/main/scala/pvu/CsaTree.scala:10:14
                      io_carry_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  wire [58:0] _csa_tree_B_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [58:0] _csa_tree_B_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:53:28
  wire [58:0] _csa_tree_A_io_sum_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  wire [58:0] _csa_tree_A_io_carry_o;	// src/main/scala/pvu/CsaTree.scala:50:28
  CsaTree_5 csa_tree_A (	// src/main/scala/pvu/CsaTree.scala:50:28
    .io_operands_i (io_operands_i[4'h0 +: 7]),	// src/main/scala/pvu/CsaTree.scala:50:28, :51:30
    .io_sum_o      (_csa_tree_A_io_sum_o),
    .io_carry_o    (_csa_tree_A_io_carry_o)
  );
  CsaTree_8 csa_tree_B (	// src/main/scala/pvu/CsaTree.scala:53:28
    .io_operands_i (io_operands_i[4'h7 +: 8]),	// src/main/scala/pvu/CsaTree.scala:53:28, :54:30
    .io_sum_o      (_csa_tree_B_io_sum_o),
    .io_carry_o    (_csa_tree_B_io_carry_o)
  );
  Compressor4to2_8 compressor (	// src/main/scala/pvu/CsaTree.scala:66:28
    .io_operands_i
      ({{{1'h0, _csa_tree_B_io_carry_o}},
        {{1'h0, _csa_tree_B_io_sum_o}},
        {{1'h0, _csa_tree_A_io_carry_o}},
        {{1'h0, _csa_tree_A_io_sum_o}}}),	// src/main/scala/pvu/CsaTree.scala:50:28, :53:28, :57:28, :58:18
    .io_sum_o      (io_sum_o),
    .io_carry_o    (io_carry_o)
  );
endmodule

module Radix4BoothMultiplier_1(	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:7:7
  input  [27:0] io_operand_a,	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
                io_operand_b,	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
  output [55:0] io_sum_o,	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
                io_carry_o	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:12:14
);

  wire [59:0]       _csaTree_io_sum_o;	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:25:23
  wire [59:0]       _csaTree_io_carry_o;	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:25:23
  wire [14:0][55:0] _genProds_io_partial_prods;	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:20:24
  GenProds_1 genProds (	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:20:24
    .io_operand_a     (io_operand_a),
    .io_operand_b     (io_operand_b),
    .io_partial_prods (_genProds_io_partial_prods)
  );
  CsaTree_9 csaTree (	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:25:23
    .io_operands_i (_genProds_io_partial_prods),	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:20:24
    .io_sum_o      (_csaTree_io_sum_o),
    .io_carry_o    (_csaTree_io_carry_o)
  );
  assign io_sum_o = _csaTree_io_sum_o[55:0];	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:7:7, :25:23, :29:14
  assign io_carry_o = _csaTree_io_carry_o[55:0];	// src/main/scala/pvu/Radix4_Booth_Multiplier.scala:7:7, :25:23, :30:14
endmodule

module IntDivider(	// src/main/scala/pvu/IntDivider.scala:9:7
  input  [13:0] io_dividend,	// src/main/scala/pvu/IntDivider.scala:10:14
                io_divisor,	// src/main/scala/pvu/IntDivider.scala:10:14
  output [27:0] io_quotient	// src/main/scala/pvu/IntDivider.scala:10:14
);

  wire [55:0] _boothMult_io_sum_o;	// src/main/scala/pvu/IntDivider.scala:26:25
  wire [55:0] _boothMult_io_carry_o;	// src/main/scala/pvu/IntDivider.scala:26:25
  wire [27:0] _reciprocalMod_io_reciprocal_o;	// src/main/scala/pvu/IntDivider.scala:17:29
  wire [41:0] _product_T = _boothMult_io_sum_o[41:0] + _boothMult_io_carry_o[41:0];	// src/main/scala/pvu/IntDivider.scala:26:25, :30:36
  IntReciprocal reciprocalMod (	// src/main/scala/pvu/IntDivider.scala:17:29
    .io_num_i        (io_divisor),
    .io_reciprocal_o (_reciprocalMod_io_reciprocal_o)
  );
  Radix4BoothMultiplier_1 boothMult (	// src/main/scala/pvu/IntDivider.scala:26:25
    .io_operand_a ({io_dividend, 14'h0}),	// src/main/scala/pvu/IntDivider.scala:22:37
    .io_operand_b (_reciprocalMod_io_reciprocal_o),	// src/main/scala/pvu/IntDivider.scala:17:29
    .io_sum_o     (_boothMult_io_sum_o),
    .io_carry_o   (_boothMult_io_carry_o)
  );
  assign io_quotient = _product_T[41:14];	// src/main/scala/pvu/IntDivider.scala:9:7, :30:36, :33:{27,41}
endmodule

module Div(	// src/main/scala/pvu/Div.scala:8:7
  input  [0:0]       io_pir_sign1_i,	// src/main/scala/pvu/Div.scala:15:14
                     io_pir_sign2_i,	// src/main/scala/pvu/Div.scala:15:14
  input  [0:0][6:0]  io_pir_exp1_i,	// src/main/scala/pvu/Div.scala:15:14
                     io_pir_exp2_i,	// src/main/scala/pvu/Div.scala:15:14
  input  [0:0][13:0] io_pir_frac1_i,	// src/main/scala/pvu/Div.scala:15:14
                     io_pir_frac2_i,	// src/main/scala/pvu/Div.scala:15:14
  output [0:0]       io_pir_sign_o,	// src/main/scala/pvu/Div.scala:15:14
  output [0:0][6:0]  io_pir_exp_o,	// src/main/scala/pvu/Div.scala:15:14
  output [0:0][29:0] io_pir_frac_o	// src/main/scala/pvu/Div.scala:15:14
);

  wire [27:0] _intdivider_io_quotient;	// src/main/scala/pvu/Div.scala:32:41
  wire        _GEN = /*cast(bit)*/io_pir_sign1_i;	// src/main/scala/pvu/Div.scala:8:7
  wire        _GEN_0 = /*cast(bit)*/io_pir_sign2_i;	// src/main/scala/pvu/Div.scala:8:7
  IntDivider intdivider (	// src/main/scala/pvu/Div.scala:32:41
    .io_dividend (io_pir_frac1_i[1'h0]),	// src/main/scala/pvu/Div.scala:33:32, :37:52
    .io_divisor  (io_pir_frac2_i[1'h0]),	// src/main/scala/pvu/Div.scala:34:32, :37:52
    .io_quotient (_intdivider_io_quotient)
  );
  assign io_pir_sign_o = /*cast(bit[0:0])*/_GEN ^ _GEN_0;	// src/main/scala/pvu/Div.scala:8:7
  assign io_pir_exp_o = {1{io_pir_exp1_i[1'h0] - io_pir_exp2_i[1'h0]}};	// src/main/scala/pvu/Div.scala:8:7, :37:52
  assign io_pir_frac_o = {1{{2'h0, _intdivider_io_quotient}}};	// src/main/scala/pvu/Div.scala:8:7, :32:41, :35:32
endmodule

module CompTree(	// src/main/scala/pvu/CompTree.scala:13:7
  input  [0:0][6:0] io_operands_i,	// src/main/scala/pvu/CompTree.scala:14:14
  output [6:0]      io_result_o	// src/main/scala/pvu/CompTree.scala:14:14
);

  assign io_result_o = io_operands_i[1'h0];	// src/main/scala/pvu/CompTree.scala:13:7, :21:17
endmodule

module FractionAlignment_DotProduct(	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:8:7
  input  [0:0][25:0] io_pir_frac_i,	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:16:14
  input  [0:0][6:0]  io_pir_exp_i,	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:16:14
  output [0:0][25:0] io_pir_frac_align,	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:16:14
  output [6:0]       io_pir_max_exp	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:16:14
);

  wire [6:0] _comptree_io_result_o;	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:25:26
  wire [6:0] _shift_amount_T = _comptree_io_result_o - io_pir_exp_i[1'h0];	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:25:26, :26:28, :43:{40,62}
  wire [6:0] shift_amount = $signed(_shift_amount_T) < 7'sh0 ? 7'h0 : _shift_amount_T;	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:43:{40,62}
  CompTree comptree (	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:25:26
    .io_operands_i (io_pir_exp_i),
    .io_result_o   (_comptree_io_result_o)
  );
  assign io_pir_frac_align =
    {1{{io_pir_frac_i[1'h0][23:0], 2'h0}
    >> ($signed(shift_amount) > 7'shE ? 7'hE : shift_amount)}};	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:8:7, :33:{25,45}, :43:62, :44:{45,51,65}
  assign io_pir_max_exp = _comptree_io_result_o;	// src/main/scala/pvu/FractionAlignment_DotProduct.scala:8:7, :25:26
endmodule

module CsaTree_13(	// src/main/scala/pvu/CsaTree.scala:7:7
  input  [0:0][29:0] io_operands_i,	// src/main/scala/pvu/CsaTree.scala:10:14
  output [29:0]      io_sum_o	// src/main/scala/pvu/CsaTree.scala:10:14
);

  assign io_sum_o = io_operands_i[1'h0];	// src/main/scala/pvu/CsaTree.scala:7:7, :22:14
endmodule

module DotProduct(	// src/main/scala/pvu/DotProduct.scala:7:7
  input              clock,	// src/main/scala/pvu/DotProduct.scala:7:7
                     reset,	// src/main/scala/pvu/DotProduct.scala:7:7
  input  [0:0]       io_pir_sign1_i,	// src/main/scala/pvu/DotProduct.scala:14:14
                     io_pir_sign2_i,	// src/main/scala/pvu/DotProduct.scala:14:14
  input  [0:0][6:0]  io_pir_exp1_i,	// src/main/scala/pvu/DotProduct.scala:14:14
                     io_pir_exp2_i,	// src/main/scala/pvu/DotProduct.scala:14:14
  input  [0:0][11:0] io_pir_frac1_i,	// src/main/scala/pvu/DotProduct.scala:14:14
                     io_pir_frac2_i,	// src/main/scala/pvu/DotProduct.scala:14:14
  output             io_pir_sign_o,	// src/main/scala/pvu/DotProduct.scala:14:14
  output [6:0]       io_pir_exp_o,	// src/main/scala/pvu/DotProduct.scala:14:14
  output [29:0]      io_pir_frac_o	// src/main/scala/pvu/DotProduct.scala:14:14
);

  wire [0:0]       _mul_io_pir_sign_o;	// src/main/scala/pvu/DotProduct.scala:32:19
  wire [0:0][6:0]  _mul_io_pir_exp_o;	// src/main/scala/pvu/DotProduct.scala:32:19
  wire [0:0][29:0] _mul_io_pir_frac_o;	// src/main/scala/pvu/DotProduct.scala:32:19
  reg  [0:0][29:0] pir_frac_cmp_tmp;	// src/main/scala/pvu/DotProduct.scala:55:31
  wire [29:0]      _pir_frac_cmp_0_T_1 = ~pir_frac_cmp_tmp[1'h0] + 30'h1;	// src/main/scala/pvu/DotProduct.scala:46:26, :55:31, :58:25, :60:{26,47}
  always @(posedge clock) begin	// src/main/scala/pvu/DotProduct.scala:7:7
    if (reset)	// src/main/scala/pvu/DotProduct.scala:7:7
      pir_frac_cmp_tmp <= '{30'h0};	// src/main/scala/pvu/DotProduct.scala:55:{31,39}
    else if (_mul_io_pir_sign_o[1'h0])	// src/main/scala/pvu/DotProduct.scala:32:19, :46:26, :59:27
      pir_frac_cmp_tmp[1'h0] <= _pir_frac_cmp_0_T_1;	// src/main/scala/pvu/DotProduct.scala:46:26, :55:31, :60:47
  end // always @(posedge)
  Mul mul (	// src/main/scala/pvu/DotProduct.scala:32:19
    .io_pir_sign1_i (io_pir_sign1_i),
    .io_pir_sign2_i (io_pir_sign2_i),
    .io_pir_exp1_i  (io_pir_exp1_i),
    .io_pir_exp2_i  (io_pir_exp2_i),
    .io_pir_frac1_i ({1{{2'h0, io_pir_frac1_i[1'h0]}}}),	// src/main/scala/pvu/DotProduct.scala:32:19, :37:22, :46:26
    .io_pir_frac2_i ({1{{2'h0, io_pir_frac2_i[1'h0]}}}),	// src/main/scala/pvu/DotProduct.scala:32:19, :37:22, :38:22, :46:26
    .io_pir_sign_o  (_mul_io_pir_sign_o),
    .io_pir_exp_o   (_mul_io_pir_exp_o),
    .io_pir_frac_o  (_mul_io_pir_frac_o)
  );
  FractionAlignment_DotProduct frac_compare (	// src/main/scala/pvu/DotProduct.scala:48:39
    .io_pir_frac_i     ({1{_mul_io_pir_frac_o[1'h0][25:0]}}),	// src/main/scala/pvu/DotProduct.scala:32:19, :46:26, :48:39, :50:30
    .io_pir_exp_i      (_mul_io_pir_exp_o),	// src/main/scala/pvu/DotProduct.scala:32:19
    .io_pir_frac_align (/* unused */),
    .io_pir_max_exp    (io_pir_exp_o)
  );
  CsaTree_13 csaTree (	// src/main/scala/pvu/DotProduct.scala:71:23
    .io_operands_i
      ({1{_mul_io_pir_sign_o[1'h0] ? _pir_frac_cmp_0_T_1 : pir_frac_cmp_tmp[1'h0]}}),	// src/main/scala/pvu/DotProduct.scala:32:19, :46:26, :55:31, :58:25, :59:{27,36}, :60:{23,47}, :62:23
    .io_sum_o      (io_pir_frac_o)
  );
  assign io_pir_sign_o = 1'h0;	// src/main/scala/pvu/DotProduct.scala:7:7, :46:26
endmodule

// external module LZC

module BarrelShifter_2(	// src/main/scala/pvu/BarrelShift.scala:13:7
  input  [29:0] io_operand_i,	// src/main/scala/pvu/BarrelShift.scala:14:14
  input  [4:0]  io_shift_amount,	// src/main/scala/pvu/BarrelShift.scala:14:14
  output [29:0] io_result_o	// src/main/scala/pvu/BarrelShift.scala:14:14
);

  wire [29:0] _temp_results_3_T_2 =
    io_shift_amount[4] ? {io_operand_i[13:0], 16'h0} : io_operand_i;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [29:0] _temp_results_2_T_2 =
    io_shift_amount[3] ? {_temp_results_3_T_2[21:0], 8'h0} : _temp_results_3_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [29:0] _temp_results_1_T_2 =
    io_shift_amount[2] ? {_temp_results_2_T_2[25:0], 4'h0} : _temp_results_2_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [29:0] _temp_results_0_T_2 =
    io_shift_amount[1] ? {_temp_results_1_T_2[27:0], 2'h0} : _temp_results_1_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  assign io_result_o =
    io_shift_amount[0] ? {_temp_results_0_T_2[28:0], 1'h0} : _temp_results_0_T_2;	// src/main/scala/pvu/BarrelShift.scala:13:7, :32:33, :42:{23,39,60}
endmodule

module FracNorm_DotProduct(	// src/main/scala/pvu/FracNorm_DotProduct.scala:11:7
  input  [29:0] io_pir_frac_i,	// src/main/scala/pvu/FracNorm_DotProduct.scala:17:14
  output [7:0]  io_exp_adjust,	// src/main/scala/pvu/FracNorm_DotProduct.scala:17:14
  output [12:0] io_pir_frac_o	// src/main/scala/pvu/FracNorm_DotProduct.scala:17:14
);

  wire [29:0] _shifter_io_result_o;	// src/main/scala/pvu/FracNorm_DotProduct.scala:46:30
  wire [4:0]  _lzcMod_cnt_o;	// src/main/scala/pvu/FracNorm_DotProduct.scala:27:37
  wire        _lzcMod_empty_o;	// src/main/scala/pvu/FracNorm_DotProduct.scala:27:37
  wire [4:0]  _exp_adjust_reg_T_2 = 5'h1 - _lzcMod_cnt_o - 5'h1;	// src/main/scala/pvu/FracNorm_DotProduct.scala:27:37, :37:{42,63}
  wire [4:0]  _exp_adjust_reg_T_10 = 5'h0 - _lzcMod_cnt_o;	// src/main/scala/pvu/FracNorm_DotProduct.scala:27:37, :36:35, :39:25
  LZC #(
    .MODE(1),
    .WIDTH(29)
  ) lzcMod (	// src/main/scala/pvu/FracNorm_DotProduct.scala:27:37
    .in_i    (io_pir_frac_i[28:0]),	// src/main/scala/pvu/FracNorm_DotProduct.scala:28:28
    .cnt_o   (_lzcMod_cnt_o),
    .empty_o (_lzcMod_empty_o)
  );
  BarrelShifter_2 shifter (	// src/main/scala/pvu/FracNorm_DotProduct.scala:46:30
    .io_operand_i    (io_pir_frac_i),
    .io_shift_amount (_lzcMod_cnt_o),	// src/main/scala/pvu/FracNorm_DotProduct.scala:27:37
    .io_result_o     (_shifter_io_result_o)
  );
  assign io_exp_adjust =
    _lzcMod_empty_o
      ? 8'h0
      : _lzcMod_cnt_o == 5'h0
          ? {{3{_exp_adjust_reg_T_2[4]}}, _exp_adjust_reg_T_2}
          : {{3{_exp_adjust_reg_T_10[4]}}, _exp_adjust_reg_T_10};	// src/main/scala/pvu/FracNorm_DotProduct.scala:11:7, :27:37, :34:22, :35:22, :36:{35,61}, :37:{22,63}, :39:{22,25}
  assign io_pir_frac_o = {_shifter_io_result_o[29:18], |(_shifter_io_result_o[16:0])};	// src/main/scala/pvu/FracNorm_DotProduct.scala:11:7, :46:30, :53:37, :54:37, :55:{27,40}
endmodule

// external module LZC

module BarrelShifter_3(	// src/main/scala/pvu/BarrelShift.scala:13:7
  input  [13:0] io_operand_i,	// src/main/scala/pvu/BarrelShift.scala:14:14
  input  [3:0]  io_shift_amount,	// src/main/scala/pvu/BarrelShift.scala:14:14
  output [13:0] io_result_o	// src/main/scala/pvu/BarrelShift.scala:14:14
);

  wire [13:0] _temp_results_2_T_2 =
    io_shift_amount[3] ? {io_operand_i[5:0], 8'h0} : io_operand_i;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [13:0] _temp_results_1_T_2 =
    io_shift_amount[2] ? {_temp_results_2_T_2[9:0], 4'h0} : _temp_results_2_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [13:0] _temp_results_0_T_2 =
    io_shift_amount[1] ? {_temp_results_1_T_2[11:0], 2'h0} : _temp_results_1_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{27,33,49,70}
  assign io_result_o =
    io_shift_amount[0] ? {_temp_results_0_T_2[12:0], 1'h0} : _temp_results_0_T_2;	// src/main/scala/pvu/BarrelShift.scala:13:7, :32:33, :42:{23,39,60}
endmodule

module FracNorm(	// src/main/scala/pvu/FracNorm.scala:10:7
  input  [0:0][13:0] io_pir_frac_i,	// src/main/scala/pvu/FracNorm.scala:16:14
  output [0:0][6:0]  io_exp_adjust,	// src/main/scala/pvu/FracNorm.scala:16:14
  output [0:0][12:0] io_pir_frac_o	// src/main/scala/pvu/FracNorm.scala:16:14
);

  wire [13:0] _shifter_io_result_o;	// src/main/scala/pvu/FracNorm.scala:48:30
  wire [3:0]  _lzcMod_cnt_o;	// src/main/scala/pvu/FracNorm.scala:29:37
  wire        _lzcMod_empty_o;	// src/main/scala/pvu/FracNorm.scala:29:37
  wire [3:0]  _exp_adjust_reg_T_2 = 4'h1 - _lzcMod_cnt_o - 4'h1;	// src/main/scala/pvu/FracNorm.scala:29:37, :39:{42,63}
  wire [3:0]  _exp_adjust_reg_T_10 = 4'h0 - _lzcMod_cnt_o;	// src/main/scala/pvu/FracNorm.scala:29:37, :38:35, :41:25
  LZC #(
    .MODE(1),
    .WIDTH(14)
  ) lzcMod (	// src/main/scala/pvu/FracNorm.scala:29:37
    .in_i    (io_pir_frac_i[1'h0]),	// src/main/scala/pvu/FracNorm.scala:30:28, :37:22
    .cnt_o   (_lzcMod_cnt_o),
    .empty_o (_lzcMod_empty_o)
  );
  BarrelShifter_3 shifter (	// src/main/scala/pvu/FracNorm.scala:48:30
    .io_operand_i    (io_pir_frac_i[1'h0]),	// src/main/scala/pvu/FracNorm.scala:30:28, :37:22
    .io_shift_amount (_lzcMod_cnt_o),	// src/main/scala/pvu/FracNorm.scala:29:37
    .io_result_o     (_shifter_io_result_o)
  );
  assign io_exp_adjust =
    {1{(_lzcMod_empty_o
          ? 7'h0
          : _lzcMod_cnt_o == 4'h0
              ? {{3{_exp_adjust_reg_T_2[3]}}, _exp_adjust_reg_T_2}
              : {{3{_exp_adjust_reg_T_10[3]}}, _exp_adjust_reg_T_10}) + 7'h2}};	// src/main/scala/pvu/FracNorm.scala:10:7, :29:37, :36:22, :37:22, :38:{35,61}, :39:{22,63}, :41:{22,25}, :58:52
  assign io_pir_frac_o = {1{{_shifter_io_result_o[13:2], _shifter_io_result_o[0]}}};	// src/main/scala/pvu/FracNorm.scala:10:7, :48:30, :55:37, :57:{30,43}
endmodule

// external module LZC

module FracNorm_2(	// src/main/scala/pvu/FracNorm.scala:10:7
  input  [0:0][29:0] io_pir_frac_i,	// src/main/scala/pvu/FracNorm.scala:16:14
  output [0:0][7:0]  io_exp_adjust,	// src/main/scala/pvu/FracNorm.scala:16:14
  output [0:0][12:0] io_pir_frac_o	// src/main/scala/pvu/FracNorm.scala:16:14
);

  wire [29:0] _shifter_io_result_o;	// src/main/scala/pvu/FracNorm.scala:48:30
  wire [4:0]  _lzcMod_cnt_o;	// src/main/scala/pvu/FracNorm.scala:29:37
  wire        _lzcMod_empty_o;	// src/main/scala/pvu/FracNorm.scala:29:37
  wire [4:0]  _exp_adjust_reg_T_2 = 5'h1 - _lzcMod_cnt_o - 5'h1;	// src/main/scala/pvu/FracNorm.scala:29:37, :39:{42,63}
  wire [4:0]  _exp_adjust_reg_T_10 = 5'h0 - _lzcMod_cnt_o;	// src/main/scala/pvu/FracNorm.scala:29:37, :38:35, :41:25
  LZC #(
    .MODE(1),
    .WIDTH(30)
  ) lzcMod (	// src/main/scala/pvu/FracNorm.scala:29:37
    .in_i    (io_pir_frac_i[1'h0]),	// src/main/scala/pvu/FracNorm.scala:30:28, :37:22
    .cnt_o   (_lzcMod_cnt_o),
    .empty_o (_lzcMod_empty_o)
  );
  BarrelShifter_2 shifter (	// src/main/scala/pvu/FracNorm.scala:48:30
    .io_operand_i    (io_pir_frac_i[1'h0]),	// src/main/scala/pvu/FracNorm.scala:30:28, :37:22
    .io_shift_amount (_lzcMod_cnt_o),	// src/main/scala/pvu/FracNorm.scala:29:37
    .io_result_o     (_shifter_io_result_o)
  );
  assign io_exp_adjust =
    {1{(_lzcMod_empty_o
          ? 8'h0
          : _lzcMod_cnt_o == 5'h0
              ? {{3{_exp_adjust_reg_T_2[4]}}, _exp_adjust_reg_T_2}
              : {{3{_exp_adjust_reg_T_10[4]}}, _exp_adjust_reg_T_10}) + 8'h12}};	// src/main/scala/pvu/FracNorm.scala:10:7, :29:37, :36:22, :37:22, :38:{35,61}, :39:{22,63}, :41:{22,25}, :58:52
  assign io_pir_frac_o =
    {1{{_shifter_io_result_o[29:18], |(_shifter_io_result_o[16:0])}}};	// src/main/scala/pvu/FracNorm.scala:10:7, :48:30, :55:37, :56:37, :57:{30,43}
endmodule

module BarrelShifter_6(	// src/main/scala/pvu/BarrelShift.scala:13:7
  input  [43:0] io_operand_i,	// src/main/scala/pvu/BarrelShift.scala:14:14
  input  [3:0]  io_shift_amount,	// src/main/scala/pvu/BarrelShift.scala:14:14
  output [43:0] io_result_o	// src/main/scala/pvu/BarrelShift.scala:14:14
);

  wire [43:0] _temp_results_2_T_2 =
    io_shift_amount[3] ? {io_operand_i[35:0], 8'h0} : io_operand_i;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [43:0] _temp_results_1_T_2 =
    io_shift_amount[2] ? {_temp_results_2_T_2[39:0], 4'h0} : _temp_results_2_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{33,49,70}
  wire [43:0] _temp_results_0_T_2 =
    io_shift_amount[1] ? {_temp_results_1_T_2[41:0], 2'h0} : _temp_results_1_T_2;	// src/main/scala/pvu/BarrelShift.scala:32:{27,33,49,70}
  assign io_result_o =
    io_shift_amount[0] ? {_temp_results_0_T_2[42:0], 1'h0} : _temp_results_0_T_2;	// src/main/scala/pvu/BarrelShift.scala:13:7, :32:33, :42:{23,39,60}
endmodule

module PositEncode_DotProduct(	// src/main/scala/pvu/PositEncode_DotProduct.scala:7:7
  input         io_pir_sign,	// src/main/scala/pvu/PositEncode_DotProduct.scala:13:14
  input  [6:0]  io_pir_exp,	// src/main/scala/pvu/PositEncode_DotProduct.scala:13:14
  input  [12:0] io_pir_frac,	// src/main/scala/pvu/PositEncode_DotProduct.scala:13:14
  output [15:0] io_posit	// src/main/scala/pvu/PositEncode_DotProduct.scala:13:14
);

  wire [43:0] _barrel_shifter_io_result_o;	// src/main/scala/pvu/PositEncode_DotProduct.scala:65:47
  wire [14:0] _value_after_round_T =
    _barrel_shifter_io_result_o[29:15]
    + {14'h0,
       _barrel_shifter_io_result_o[14]
         & ((|(_barrel_shifter_io_result_o[13:0])) | _barrel_shifter_io_result_o[15])};	// src/main/scala/pvu/PositEncode_DotProduct.scala:65:47, :76:42, :79:38, :80:{38,57}, :81:{38,52,72}, :82:47
  BarrelShifter_6 barrel_shifter (	// src/main/scala/pvu/PositEncode_DotProduct.scala:65:47
    .io_operand_i
      ({io_pir_exp[6] ? 15'h1 : 15'h7FFE, io_pir_exp[1:0], io_pir_frac[11:0], 15'h0}),	// src/main/scala/pvu/PositEncode_DotProduct.scala:29:29, :36:15, :38:23, :39:{16,46}, :49:55, :64:53
    .io_shift_amount
      ((io_pir_exp[6] ? ~(io_pir_exp[5:2]) + 4'h2 : io_pir_exp[5:2] + 4'h2) - 4'h1),	// src/main/scala/pvu/PositEncode_DotProduct.scala:28:{16,29}, :38:23, :44:{26,45,62,79}, :56:112
    .io_result_o     (_barrel_shifter_io_result_o)
  );
  assign io_posit =
    io_pir_frac[12]
      ? (io_pir_sign
           ? {1'h1, ~_value_after_round_T + 15'h1}
           : {1'h0, _value_after_round_T})
      : 16'h0;	// src/main/scala/pvu/PositEncode_DotProduct.scala:7:7, :23:31, :36:15, :82:47, :87:{18,43,49,68,79}, :88:18
endmodule

module BarrelShifter_7(	// src/main/scala/pvu/BarrelShift.scala:13:7
  input  [43:0] io_operand_i,	// src/main/scala/pvu/BarrelShift.scala:14:14
  input  [3:0]  io_shift_amount,	// src/main/scala/pvu/BarrelShift.scala:14:14
  output [43:0] io_result_o	// src/main/scala/pvu/BarrelShift.scala:14:14
);

  wire [43:0] _temp_results_2_T_2 =
    io_shift_amount[3] ? {8'h0, io_operand_i[43:8]} : io_operand_i;	// src/main/scala/pvu/BarrelShift.scala:35:{33,49,70}
  wire [43:0] _temp_results_1_T_2 =
    io_shift_amount[2] ? {4'h0, _temp_results_2_T_2[43:4]} : _temp_results_2_T_2;	// src/main/scala/pvu/BarrelShift.scala:35:{33,49,70}
  wire [43:0] _temp_results_0_T_2 =
    io_shift_amount[1] ? {2'h0, _temp_results_1_T_2[43:2]} : _temp_results_1_T_2;	// src/main/scala/pvu/BarrelShift.scala:35:{27,33,49,70}
  assign io_result_o =
    io_shift_amount[0] ? {1'h0, _temp_results_0_T_2[43:1]} : _temp_results_0_T_2;	// src/main/scala/pvu/BarrelShift.scala:13:7, :35:33, :45:{23,39,60}
endmodule

module PositEncode(	// src/main/scala/pvu/PositEncode.scala:7:7
  input  [0:0]       io_pir_sign,	// src/main/scala/pvu/PositEncode.scala:13:14
  input  [0:0][6:0]  io_pir_exp,	// src/main/scala/pvu/PositEncode.scala:13:14
  input  [0:0][12:0] io_pir_frac,	// src/main/scala/pvu/PositEncode.scala:13:14
  output [0:0][15:0] io_posit	// src/main/scala/pvu/PositEncode.scala:13:14
);

  wire [43:0] _barrel_shifter_io_result_o;	// src/main/scala/pvu/PositEncode.scala:84:32
  wire [14:0] _value_after_round_0_T =
    _barrel_shifter_io_result_o[29:15]
    + {14'h0,
       _barrel_shifter_io_result_o[14]
         & ((|(_barrel_shifter_io_result_o[13:0])) | _barrel_shifter_io_result_o[15])};	// src/main/scala/pvu/PositEncode.scala:84:32, :99:49, :102:41, :103:{41,60}, :104:{38,52,75}, :105:50
  BarrelShifter_7 barrel_shifter (	// src/main/scala/pvu/PositEncode.scala:84:32
    .io_operand_i
      ({io_pir_exp[1'h0][6] ? 15'h1 : 15'h7FFE,
        io_pir_exp[1'h0][1:0],
        io_pir_frac[1'h0][11:0],
        15'h0}),	// src/main/scala/pvu/PositEncode.scala:24:35, :31:33, :32:33, :42:19, :45:31, :46:{21,54}, :62:65, :83:45, :115:90
    .io_shift_amount
      ((io_pir_exp[1'h0][6]
          ? ~(io_pir_exp[1'h0][5:2]) + 4'h2
          : io_pir_exp[1'h0][5:2] + 4'h2) - 4'h1),	// src/main/scala/pvu/PositEncode.scala:31:{17,33}, :45:31, :53:{27,49,69,89}, :73:123, :115:90
    .io_result_o     (_barrel_shifter_io_result_o)
  );
  assign io_posit =
    {1{io_pir_frac[1'h0][12]
         ? (io_pir_sign[1'h0]
              ? {1'h1, ~_value_after_round_0_T + 15'h1}
              : {1'h0, _value_after_round_0_T})
         : 16'h0}};	// src/main/scala/pvu/PositEncode.scala:7:7, :24:35, :42:19, :105:50, :115:{23,39,51,57,79,90}, :116:23
endmodule

module PvuTop(	// src/main/scala/pvu/PvuTop.scala:16:8
  input         clock,	// src/main/scala/pvu/PvuTop.scala:16:8
                reset,	// src/main/scala/pvu/PvuTop.scala:16:8
  input  [15:0] io_posit_i1_0,	// src/main/scala/pvu/PvuTop.scala:23:15
                io_posit_i2_0,	// src/main/scala/pvu/PvuTop.scala:23:15
  input  [2:0]  io_op,	// src/main/scala/pvu/PvuTop.scala:23:15
  output [15:0] io_posit_o_0,	// src/main/scala/pvu/PvuTop.scala:23:15
                io_posit_dot_o	// src/main/scala/pvu/PvuTop.scala:23:15
);

  wire [0:0][15:0] _encode_io_posit;	// src/main/scala/pvu/PvuTop.scala:249:24
  wire [15:0]      _encode_dot_io_posit;	// src/main/scala/pvu/PvuTop.scala:242:28
  wire [0:0][7:0]  _frac_norm_io_exp_adjust;	// src/main/scala/pvu/PvuTop.scala:212:27
  wire [0:0][12:0] _frac_norm_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:212:27
  wire [0:0][6:0]  _frac_norm_sub_io_exp_adjust;	// src/main/scala/pvu/PvuTop.scala:207:31
  wire [0:0][12:0] _frac_norm_sub_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:207:31
  wire [0:0][6:0]  _frac_norm_add_io_exp_adjust;	// src/main/scala/pvu/PvuTop.scala:202:31
  wire [0:0][12:0] _frac_norm_add_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:202:31
  wire [7:0]       _frac_norm_dot_io_exp_adjust;	// src/main/scala/pvu/PvuTop.scala:196:29
  wire [12:0]      _frac_norm_dot_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:196:29
  wire             _dotproduct_io_pir_sign_o;	// src/main/scala/pvu/PvuTop.scala:164:27
  wire [29:0]      _dotproduct_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:164:27
  wire [0:0]       _div_io_pir_sign_o;	// src/main/scala/pvu/PvuTop.scala:150:21
  wire [0:0][6:0]  _div_io_pir_exp_o;	// src/main/scala/pvu/PvuTop.scala:150:21
  wire [0:0][29:0] _div_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:150:21
  wire [0:0]       _mul_io_pir_sign_o;	// src/main/scala/pvu/PvuTop.scala:136:21
  wire [0:0][6:0]  _mul_io_pir_exp_o;	// src/main/scala/pvu/PvuTop.scala:136:21
  wire [0:0][29:0] _mul_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:136:21
  wire [0:0]       _sub_io_pir_sign_o;	// src/main/scala/pvu/PvuTop.scala:114:27
  wire [0:0][6:0]  _sub_io_pir_exp_o;	// src/main/scala/pvu/PvuTop.scala:114:27
  wire [0:0][13:0] _sub_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:114:27
  wire [0:0][13:0] _fracalign_1_io_pir_frac1_align;	// src/main/scala/pvu/PvuTop.scala:113:27
  wire [0:0][13:0] _fracalign_1_io_pir_frac2_align;	// src/main/scala/pvu/PvuTop.scala:113:27
  wire [0:0]       _add_io_pir_sign_o;	// src/main/scala/pvu/PvuTop.scala:88:27
  wire [0:0][6:0]  _add_io_pir_exp_o;	// src/main/scala/pvu/PvuTop.scala:88:27
  wire [0:0][13:0] _add_io_pir_frac_o;	// src/main/scala/pvu/PvuTop.scala:88:27
  wire [0:0][13:0] _fracalign_io_pir_frac1_align;	// src/main/scala/pvu/PvuTop.scala:87:27
  wire [0:0][13:0] _fracalign_io_pir_frac2_align;	// src/main/scala/pvu/PvuTop.scala:87:27
  wire [0:0]       _decode2_io_Sign;	// src/main/scala/pvu/PvuTop.scala:43:23
  wire [0:0][6:0]  _decode2_io_Exp;	// src/main/scala/pvu/PvuTop.scala:43:23
  wire [0:0][11:0] _decode2_io_Frac;	// src/main/scala/pvu/PvuTop.scala:43:23
  wire [0:0]       _decode1_io_Sign;	// src/main/scala/pvu/PvuTop.scala:42:23
  wire [0:0][6:0]  _decode1_io_Exp;	// src/main/scala/pvu/PvuTop.scala:42:23
  wire [0:0][11:0] _decode1_io_Frac;	// src/main/scala/pvu/PvuTop.scala:42:23
  wire             _GEN = io_op == 3'h1;	// src/main/scala/pvu/PvuTop.scala:83:14
  wire [13:0]      _GEN_0 = _GEN ? _add_io_pir_frac_o[1'h0] : 14'h0;	// src/main/scala/pvu/PvuTop.scala:71:28, :73:28, :83:{14,22}, :88:27, :104:22
  wire             _GEN_1 = io_op == 3'h2;	// src/main/scala/pvu/PvuTop.scala:109:20
  wire             _GEN_2 = io_op == 3'h3;	// src/main/scala/pvu/PvuTop.scala:135:20
  wire             _GEN_3 = io_op == 3'h4;	// src/main/scala/pvu/PvuTop.scala:149:20
  wire             _GEN_4 = io_op == 3'h5;	// src/main/scala/pvu/PvuTop.scala:163:20
  wire             _GEN_5 = _GEN | _GEN_1 | _GEN_2 | _GEN_3;	// src/main/scala/pvu/PvuTop.scala:79:16, :83:{14,22}, :109:{20,28}, :135:{20,28}, :149:{20,28}, :163:28
  wire [29:0]      _GEN_6 = {17'h0, _frac_norm_io_pir_frac_o[1'h0]};	// src/main/scala/pvu/PvuTop.scala:71:28, :198:31, :212:27, :214:29
  wire [7:0][29:0] _GEN_7 =
    {{30'h0},
     {30'h0},
     {30'h0},
     {_GEN_6},
     {_GEN_6},
     {{17'h0, _frac_norm_sub_io_pir_frac_o[1'h0]}},
     {{17'h0, _frac_norm_add_io_pir_frac_o[1'h0]}},
     {30'h0}};	// src/main/scala/pvu/PvuTop.scala:71:28, :79:16, :83:14, :109:20, :135:28, :149:28, :163:{20,28}, :192:{23,33}, :195:22, :198:31, :201:28, :202:31, :204:33, :206:28, :207:31, :209:33, :211:45, :214:29
  wire [7:0][6:0]  _GEN_8 =
    {{7'h0},
     {7'h0},
     {7'h0},
     {_frac_norm_io_exp_adjust[1'h0][6:0]},
     {_frac_norm_io_exp_adjust[1'h0][6:0]},
     {_frac_norm_sub_io_exp_adjust[1'h0]},
     {_frac_norm_add_io_exp_adjust[1'h0]},
     {7'h0}};	// src/main/scala/pvu/PvuTop.scala:71:28, :79:16, :83:14, :109:20, :135:28, :149:28, :163:{20,28}, :190:{23,33}, :195:22, :201:28, :202:31, :205:33, :206:28, :207:31, :210:33, :211:45, :212:27, :215:29, :227:{28,38}
  `ifndef SYNTHESIS	// src/main/scala/pvu/PvuTop.scala:179:10
    always @(posedge clock) begin	// src/main/scala/pvu/PvuTop.scala:179:10
      if ((`PRINTF_COND_) & ~reset) begin	// src/main/scala/pvu/PvuTop.scala:179:10, :218:9
        $fwrite(32'h80000002, "pir_frac_rst_add: %b\n", _GEN_0);	// src/main/scala/pvu/PvuTop.scala:73:28, :83:22, :104:22, :179:10
        $fwrite(32'h80000002, "pir_frac_normed: %b\n", _GEN_7[io_op]);	// src/main/scala/pvu/PvuTop.scala:79:16, :83:14, :109:20, :135:28, :149:28, :163:{20,28}, :179:10, :192:23, :195:22, :201:28, :204:33, :206:28, :209:33, :211:45, :214:29, :218:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [0:0][13:0] _GEN_9 = {1{{2'h0, _decode1_io_Frac[1'h0]}}};	// src/main/scala/pvu/PvuTop.scala:42:23, :71:28, :83:14, :91:30, :136:21, :142:24
  wire [0:0][13:0] _GEN_10 = {1{{2'h0, _decode2_io_Frac[1'h0]}}};	// src/main/scala/pvu/PvuTop.scala:43:23, :71:28, :83:14, :93:30, :136:21, :143:24
  PositDecode decode1 (	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_posit ({1{io_posit_i1_0}}),	// src/main/scala/pvu/PvuTop.scala:16:8
    .io_Sign  (_decode1_io_Sign),
    .io_Exp   (_decode1_io_Exp),
    .io_Frac  (_decode1_io_Frac)
  );
  PositDecode decode2 (	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_posit ({1{io_posit_i2_0}}),	// src/main/scala/pvu/PvuTop.scala:16:8
    .io_Sign  (_decode2_io_Sign),
    .io_Exp   (_decode2_io_Exp),
    .io_Frac  (_decode2_io_Frac)
  );
  FractionAlignment_AddSub fracalign (	// src/main/scala/pvu/PvuTop.scala:87:27
    .io_pir_frac1_i     (_decode1_io_Frac),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_frac2_i     (_decode2_io_Frac),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i      (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i      (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_align (_fracalign_io_pir_frac1_align),
    .io_pir_frac2_align (_fracalign_io_pir_frac2_align),
    .io_pir_max_exp     (/* unused */)
  );
  Add add (	// src/main/scala/pvu/PvuTop.scala:88:27
    .io_pir_sign1_i       (_decode1_io_Sign),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_sign2_i       (_decode2_io_Sign),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i        (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i        (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_aligned (_fracalign_io_pir_frac1_align),	// src/main/scala/pvu/PvuTop.scala:87:27
    .io_pir_frac2_aligned (_fracalign_io_pir_frac2_align),	// src/main/scala/pvu/PvuTop.scala:87:27
    .io_pir_sign_o        (_add_io_pir_sign_o),
    .io_pir_exp_o         (_add_io_pir_exp_o),
    .io_pir_frac_o        (_add_io_pir_frac_o),
    .io_overflow          (/* unused */),
    .io_frac_truncate     (/* unused */)
  );
  FractionAlignment_AddSub fracalign_1 (	// src/main/scala/pvu/PvuTop.scala:113:27
    .io_pir_frac1_i     (_decode1_io_Frac),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_frac2_i     (_decode2_io_Frac),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i      (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i      (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_align (_fracalign_1_io_pir_frac1_align),
    .io_pir_frac2_align (_fracalign_1_io_pir_frac2_align),
    .io_pir_max_exp     (/* unused */)
  );
  Sub sub (	// src/main/scala/pvu/PvuTop.scala:114:27
    .io_pir_sign1_i       (_decode1_io_Sign),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_sign2_i       (_decode2_io_Sign),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i        (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i        (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_aligned (_fracalign_1_io_pir_frac1_align),	// src/main/scala/pvu/PvuTop.scala:113:27
    .io_pir_frac2_aligned (_fracalign_1_io_pir_frac2_align),	// src/main/scala/pvu/PvuTop.scala:113:27
    .io_pir_sign_o        (_sub_io_pir_sign_o),
    .io_pir_exp_o         (_sub_io_pir_exp_o),
    .io_pir_frac_o        (_sub_io_pir_frac_o),
    .io_overflow          (/* unused */),
    .io_frac_truncate     (/* unused */)
  );
  Mul mul (	// src/main/scala/pvu/PvuTop.scala:136:21
    .io_pir_sign1_i (_decode1_io_Sign),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_sign2_i (_decode2_io_Sign),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i  (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i  (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_i (_GEN_9),	// src/main/scala/pvu/PvuTop.scala:136:21
    .io_pir_frac2_i (_GEN_10),	// src/main/scala/pvu/PvuTop.scala:136:21
    .io_pir_sign_o  (_mul_io_pir_sign_o),
    .io_pir_exp_o   (_mul_io_pir_exp_o),
    .io_pir_frac_o  (_mul_io_pir_frac_o)
  );
  Div div (	// src/main/scala/pvu/PvuTop.scala:150:21
    .io_pir_sign1_i (_decode1_io_Sign),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_sign2_i (_decode2_io_Sign),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i  (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i  (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_i (_GEN_9),	// src/main/scala/pvu/PvuTop.scala:136:21
    .io_pir_frac2_i (_GEN_10),	// src/main/scala/pvu/PvuTop.scala:136:21
    .io_pir_sign_o  (_div_io_pir_sign_o),
    .io_pir_exp_o   (_div_io_pir_exp_o),
    .io_pir_frac_o  (_div_io_pir_frac_o)
  );
  DotProduct dotproduct (	// src/main/scala/pvu/PvuTop.scala:164:27
    .clock          (clock),
    .reset          (reset),
    .io_pir_sign1_i (_decode1_io_Sign),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_sign2_i (_decode2_io_Sign),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_exp1_i  (_decode1_io_Exp),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_exp2_i  (_decode2_io_Exp),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_frac1_i (_decode1_io_Frac),	// src/main/scala/pvu/PvuTop.scala:42:23
    .io_pir_frac2_i (_decode2_io_Frac),	// src/main/scala/pvu/PvuTop.scala:43:23
    .io_pir_sign_o  (_dotproduct_io_pir_sign_o),
    .io_pir_exp_o   (/* unused */),
    .io_pir_frac_o  (_dotproduct_io_pir_frac_o)
  );
  FracNorm_DotProduct frac_norm_dot (	// src/main/scala/pvu/PvuTop.scala:196:29
    .io_pir_frac_i (_GEN_5 | ~_GEN_4 ? 30'h0 : _dotproduct_io_pir_frac_o),	// src/main/scala/pvu/PvuTop.scala:79:16, :81:16, :83:22, :109:28, :135:28, :149:28, :163:{20,28}, :164:27, :192:{23,33}
    .io_exp_adjust (_frac_norm_dot_io_exp_adjust),
    .io_pir_frac_o (_frac_norm_dot_io_pir_frac_o)
  );
  FracNorm frac_norm_add (	// src/main/scala/pvu/PvuTop.scala:202:31
    .io_pir_frac_i ({1{_GEN_0}}),	// src/main/scala/pvu/PvuTop.scala:73:28, :83:22, :104:22
    .io_exp_adjust (_frac_norm_add_io_exp_adjust),
    .io_pir_frac_o (_frac_norm_add_io_pir_frac_o)
  );
  FracNorm frac_norm_sub (	// src/main/scala/pvu/PvuTop.scala:207:31
    .io_pir_frac_i ({1{_GEN | ~_GEN_1 ? 14'h0 : _sub_io_pir_frac_o[1'h0]}}),	// src/main/scala/pvu/PvuTop.scala:60:33, :71:28, :73:28, :74:28, :83:{14,22}, :109:{20,28}, :114:27, :130:22
    .io_exp_adjust (_frac_norm_sub_io_exp_adjust),
    .io_pir_frac_o (_frac_norm_sub_io_pir_frac_o)
  );
  FracNorm_2 frac_norm (	// src/main/scala/pvu/PvuTop.scala:212:27
    .io_pir_frac_i
      ({1{_GEN | _GEN_1
            ? 30'h0
            : _GEN_2
                ? _mul_io_pir_frac_o[1'h0]
                : _GEN_3 ? _div_io_pir_frac_o[1'h0] : 30'h0}}),	// src/main/scala/pvu/PvuTop.scala:61:33, :71:28, :75:28, :83:{14,22}, :109:{20,28}, :135:{20,28}, :136:21, :147:25, :149:{20,28}, :150:21, :161:25, :192:{23,33}
    .io_exp_adjust (_frac_norm_io_exp_adjust),
    .io_pir_frac_o (_frac_norm_io_pir_frac_o)
  );
  PositEncode_DotProduct encode_dot (	// src/main/scala/pvu/PvuTop.scala:242:28
    .io_pir_sign (~_GEN_5 & _GEN_4 & _dotproduct_io_pir_sign_o),	// src/main/scala/pvu/PvuTop.scala:79:16, :83:22, :109:28, :135:28, :149:28, :163:{20,28}, :164:27
    .io_pir_exp  (_GEN_4 ? _frac_norm_dot_io_exp_adjust[6:0] : 7'h0),	// src/main/scala/pvu/PvuTop.scala:163:20, :190:{23,33}, :196:29, :199:31, :227:{28,38}, :228:28, :230:22, :231:30
    .io_pir_frac (_GEN_4 ? _frac_norm_dot_io_pir_frac_o : 13'h0),	// src/main/scala/pvu/PvuTop.scala:163:20, :192:{23,33}, :193:23, :195:22, :196:29, :198:31
    .io_posit    (_encode_dot_io_posit)
  );
  PositEncode encode (	// src/main/scala/pvu/PvuTop.scala:249:24
    .io_pir_sign
      ({1{_GEN
            ? _add_io_pir_sign_o[1'h0]
            : _GEN_1
                ? _sub_io_pir_sign_o[1'h0]
                : _GEN_2
                    ? _mul_io_pir_sign_o[1'h0]
                    : _GEN_3 & _div_io_pir_sign_o[1'h0]}}),	// src/main/scala/pvu/PvuTop.scala:57:33, :71:28, :83:{14,22}, :88:27, :102:22, :109:{20,28}, :114:27, :128:22, :135:{20,28}, :136:21, :145:25, :149:{20,28}, :150:21, :159:25
    .io_pir_exp
      ({1{_GEN_4
            ? 7'h0
            : (_GEN
                 ? _add_io_pir_exp_o[1'h0]
                 : _GEN_1
                     ? _sub_io_pir_exp_o[1'h0]
                     : _GEN_2
                         ? _mul_io_pir_exp_o[1'h0]
                         : _GEN_3 ? _div_io_pir_exp_o[1'h0] : 7'h0) + _GEN_8[io_op]}}),	// src/main/scala/pvu/PvuTop.scala:71:28, :72:28, :79:16, :83:{14,22}, :88:27, :103:22, :109:{20,28}, :114:27, :129:22, :135:{20,28}, :136:21, :146:25, :149:{20,28}, :150:21, :160:25, :163:{20,28}, :190:{23,33}, :195:22, :201:28, :205:33, :206:28, :210:33, :211:45, :215:29, :223:34, :227:{28,38}, :230:22, :234:{31,49}
    .io_pir_frac ({1{_GEN_7[io_op][12:0]}}),	// src/main/scala/pvu/PvuTop.scala:79:16, :83:14, :109:20, :135:28, :149:28, :163:{20,28}, :192:23, :195:22, :201:28, :204:33, :206:28, :209:33, :211:45, :214:29, :249:24, :252:24
    .io_posit    (_encode_io_posit)
  );
  assign io_posit_o_0 = _GEN_4 ? 16'h0 : _encode_io_posit[1'h0];	// src/main/scala/pvu/PvuTop.scala:16:8, :71:28, :163:20, :241:22, :247:{28,38}, :249:24, :253:24
  assign io_posit_dot_o = _GEN_4 ? _encode_dot_io_posit : 16'h0;	// src/main/scala/pvu/PvuTop.scala:16:8, :163:20, :241:22, :242:28, :246:28, :247:{28,38}, :254:24
endmodule


// ----- 8< ----- FILE "./lzc.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.0
// Copyright 2016 ETH Zurich and University of Bologna.
// Copyright and related rights are licensed under the Solderpad Hardware
// License, Version 0.51 (the "License"); you may not use this file except in
// compliance with the License.  You may obtain a copy of the License at
// http://solderpad.org/licenses/SHL-0.51. Unless required by applicable law
// or agreed to in writing, software, hardware and materials distributed under
// this License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
// CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.

/// cf_math_pkg: Constant Function Implementations of Mathematical Functions for HDL Elaboration
///
/// This package contains a collection of mathematical functions that are commonly used when defining
/// the value of constants in HDL code.  These functions are implemented as Verilog constants
/// functions.  Introduced in Verilog 2001 (IEEE Std 1364-2001), a constant function (§ 10.3.5) is a
/// function whose value can be evaluated at compile time or during elaboration.  A constant function
/// must be called with arguments that are constants.
package cf_math_pkg;

    /// Ceiled Division of Two Natural Numbers
    ///
    /// Returns the quotient of two natural numbers, rounded towards plus infinity.
    function automatic integer ceil_div (input longint dividend, input longint divisor);
        automatic longint remainder;

        // pragma translate_off
        `ifndef VERILATOR
        if (dividend < 0) begin
            $fatal(1, "Dividend %0d is not a natural number!", dividend);
        end

        if (divisor < 0) begin
            $fatal(1, "Divisor %0d is not a natural number!", divisor);
        end

        if (divisor == 0) begin
            $fatal(1, "Division by zero!");
        end
        `endif
        // pragma translate_on

        remainder = dividend;
        for (ceil_div = 0; remainder > 0; ceil_div++) begin
            remainder = remainder - divisor;
        end
    endfunction

    function automatic integer clog(input integer n);
        begin
            n = n-1;
            for(clog=0; n>0; clog=clog+1)
                n = n>>1;
        end
    endfunction
    /// Index width required to be able to represent up to `num_idx` indices as a binary
    /// encoded signal.
    /// Ensures that the minimum width if an index signal is `1`, regardless of parametrization.
    ///
    /// Sample usage in type definition:
    /// As parameter:
    ///   `parameter type idx_t = logic[cf_math_pkg::idx_width(NumIdx)-1:0]`
    /// As typedef:
    ///   `typedef logic [cf_math_pkg::idx_width(NumIdx)-1:0] idx_t`
    function automatic integer unsigned idx_width (input integer unsigned num_idx);
        return (num_idx > 32'd1) ? unsigned'(clog(num_idx)) : 32'd1;
    endfunction

endpackage

// Copyright (c) 2018 - 2019 ETH Zurich, University of Bologna
// All rights reserved.
//
// This code is under development and not yet released to the public.
// Until it is released, the code is under the copyright of ETH Zurich and
// the University of Bologna, and may contain confidential and/or unpublished
// work. Any reuse/redistribution is strictly forbidden without written
// permission from ETH Zurich.
//
// Bug fixes and contributions will eventually be released under the
// SolderPad open hardware license in the context of the PULP platform
// (http://www.pulp-platform.org), under the copyright of ETH Zurich and the
// University of Bologna.

/// A trailing zero counter / leading zero counter.
/// Set MODE to 0 for trailing zero counter => cnt_o is the number of trailing zeros (from the LSB)
/// Set MODE to 1 for leading zero counter  => cnt_o is the number of leading zeros  (from the MSB)
/// If the input does not contain a zero, `empty_o` is asserted. Additionally `cnt_o` contains
/// the maximum number of zeros - 1. For example:
///   in_i = 000_0000, empty_o = 1, cnt_o = 6 (mode = 0)
///   in_i = 000_0001, empty_o = 0, cnt_o = 0 (mode = 0)
///   in_i = 000_1000, empty_o = 0, cnt_o = 3 (mode = 0)
/// Furthermore, this unit contains a more efficient implementation for Verilator (simulation only).
/// This speeds up simulation significantly.
module LZC #(
  /// The width of the input vector.
  parameter int unsigned WIDTH = 2,
  /// Mode selection: 0 -> trailing zero, 1 -> leading zero
  parameter bit          MODE  = 1'b0,
  /// Dependent parameter. Do **not** change!
  ///
  /// Width of the output signal with the zero count.
  parameter int unsigned CNT_WIDTH = cf_math_pkg::idx_width(WIDTH)
) (
  /// Input vector to be counted.
  input  logic [WIDTH-1:0]     in_i,
  /// Count of the leading / trailing zeros.
  output logic [CNT_WIDTH-1:0] cnt_o,
  /// Counter is empty: Asserted if all bits in in_i are zero.
  output logic                 empty_o
);

  if (WIDTH == 1) begin : gen_degenerate_lzc

    assign cnt_o[0] = !in_i[0];
    assign empty_o = !in_i[0];

  end else begin : gen_lzc

    localparam int unsigned NumLevels = cf_math_pkg::clog(WIDTH);

    // pragma translate_off
    initial begin
      assert(WIDTH > 0) else $fatal(1, "input must be at least one bit wide");
    end
    // pragma translate_on

    logic [WIDTH-1:0][NumLevels-1:0] index_lut;
    logic [2**NumLevels-1:0] sel_nodes;
    logic [2**NumLevels-1:0][NumLevels-1:0] index_nodes;

    logic [WIDTH-1:0] in_tmp;

    // reverse vector if required
    always_comb begin : flip_vector
      for (int unsigned i = 0; i < WIDTH; i++) begin
        in_tmp[i] = (MODE) ? in_i[WIDTH-1-i] : in_i[i];
      end
    end

    for (genvar j = 0; unsigned'(j) < WIDTH; j++) begin : g_index_lut
      assign index_lut[j] = (NumLevels)'(unsigned'(j));
    end

    for (genvar level = 0; unsigned'(level) < NumLevels; level++) begin : g_levels
      if (unsigned'(level) == NumLevels - 1) begin : g_last_level
        for (genvar k = 0; k < 2 ** level; k++) begin : g_level
          // if two successive indices are still in the vector...
          if (unsigned'(k) * 2 < WIDTH - 1) begin : g_reduce
            assign sel_nodes[2 ** level - 1 + k] = in_tmp[k * 2] | in_tmp[k * 2 + 1];
            assign index_nodes[2 ** level - 1 + k] = (in_tmp[k * 2] == 1'b1)
              ? index_lut[k * 2] :
                index_lut[k * 2 + 1];
          end
          // if only the first index is still in the vector...
          if (unsigned'(k) * 2 == WIDTH - 1) begin : g_base
            assign sel_nodes[2 ** level - 1 + k] = in_tmp[k * 2];
            assign index_nodes[2 ** level - 1 + k] = index_lut[k * 2];
          end
          // if index is out of range
          if (unsigned'(k) * 2 > WIDTH - 1) begin : g_out_of_range
            assign sel_nodes[2 ** level - 1 + k] = 1'b0;
            assign index_nodes[2 ** level - 1 + k] = '0;
          end
        end
      end else begin : g_not_last_level
        for (genvar l = 0; l < 2 ** level; l++) begin : g_level
          assign sel_nodes[2 ** level - 1 + l] =
              sel_nodes[2 ** (level + 1) - 1 + l * 2] | sel_nodes[2 ** (level + 1) - 1 + l * 2 + 1];
          assign index_nodes[2 ** level - 1 + l] = (sel_nodes[2 ** (level + 1) - 1 + l * 2] == 1'b1)
            ? index_nodes[2 ** (level + 1) - 1 + l * 2] :
              index_nodes[2 ** (level + 1) - 1 + l * 2 + 1];
        end
      end
    end

    assign cnt_o = NumLevels > unsigned'(0) ? index_nodes[0] : {(cf_math_pkg::clog(WIDTH)) {1'b0}};
    assign empty_o = NumLevels > unsigned'(0) ? ~sel_nodes[0] : ~(|in_i);

  end : gen_lzc

endmodule : LZC

